"""Shared scaffold for rendered AWS Glue jobs (batch and streaming)."""

from __future__ import annotations

from contractforge_core.semantic import SemanticContract
from contractforge_aws.rendering.iceberg_config import render_create_namespace_sql, resolve_iceberg_warehouse
from contractforge_aws.rendering.names import glue_database_name
from contractforge_aws.preparation import (
    preparation_requires_flatten,
    preparation_requires_functions,
    preparation_requires_window,
    render_flatten_helper,
)
from contractforge_aws.security import render_secret_resolver_helper
from contractforge_aws.sources import (
    source_requires_http_basic_helper,
    source_requires_http_fetch,
    source_requires_rds_iam,
    source_requires_rest_helper,
    source_requires_secret_resolver,
)
from contractforge_aws.sources.http_file import render_http_basic_auth_helper, render_http_file_helper
from contractforge_aws.sources.rds_iam import render_rds_iam_token_helper
from contractforge_aws.sources.rest_api import render_rest_api_helper
from contractforge_aws.write_modes import write_requires_functions


def render_job_preamble(
    contract: SemanticContract,
    source: dict,
    *,
    environment_parameters: dict[str, object] | None = None,
) -> list[str]:
    """Render the shared job header: docstring, imports, helpers and Glue/Iceberg init."""

    warehouse = resolve_iceberg_warehouse(contract, environment_parameters=environment_parameters)
    needs_secret_resolver = source_requires_secret_resolver(source)
    needs_rds_iam = source_requires_rds_iam(source)
    needs_boto3 = needs_secret_resolver or needs_rds_iam
    runtime_note = (
        "Credentials are resolved at runtime (Secrets Manager / RDS IAM); no credential is embedded in this script."
        if needs_boto3
        else "This script intentionally contains no boto3 calls; Glue supplies the Spark runtime."
    )
    return [
        '"""Generated by ContractForge AWS adapter.',
        "",
        "Runtime target: AWS Glue Spark with Apache Iceberg.",
        runtime_note,
        '"""',
        "",
        "from awsglue.context import GlueContext",
        "from awsglue.job import Job",
        "from awsglue.utils import getResolvedOptions",
        "from datetime import datetime, timezone",
        "from pyspark.context import SparkContext",
        "from uuid import uuid4",
        *_function_import_lines(contract),
        *_runtime_import_lines(needs_boto3=needs_boto3, needs_secret_resolver=needs_secret_resolver),
        "import sys",
        "import traceback",
        "",
        *_runtime_helper_lines(needs_secret_resolver=needs_secret_resolver, needs_rds_iam=needs_rds_iam),
        *_source_helper_lines(source),
        *_preparation_helper_lines(contract),
        "args = getResolvedOptions(sys.argv, ['JOB_NAME'])",
        "sc = SparkContext.getOrCreate()",
        "glue_context = GlueContext(sc)",
        "spark = glue_context.spark_session",
        "job = Job(glue_context)",
        "job.init(args['JOB_NAME'], args)",
        "",
        "# Shared run identity for all control-table evidence written by this job.",
        "_cf_run_now = datetime.now(timezone.utc)",
        "def _cf_runtime_arg(name, default=None):",
        "    flag = '--' + name",
        "    for idx, value in enumerate(sys.argv):",
        "        if value == flag and idx + 1 < len(sys.argv):",
        "            return sys.argv[idx + 1]",
        "        if value.startswith(flag + '='):",
        "            return value.split('=', 1)[1]",
        "    return default",
        "_cf_job_run_id = _cf_runtime_arg('JOB_RUN_ID')",
        "_cf_parent_run_id = _cf_runtime_arg('CONTRACTFORGE_PARENT_RUN_ID')",
        "_cf_run_group_id = _cf_runtime_arg('CONTRACTFORGE_RUN_GROUP_ID')",
        "_cf_master_job_id = _cf_runtime_arg('CONTRACTFORGE_MASTER_JOB_ID') or args['JOB_NAME']",
        "_cf_master_run_id = _cf_runtime_arg('CONTRACTFORGE_MASTER_RUN_ID') or _cf_job_run_id",
        "_cf_run_id_suffix = _cf_job_run_id or (_cf_run_now.strftime('%Y%m%dT%H%M%SZ') + ':' + uuid4().hex)",
        "_cf_run_id = args['JOB_NAME'] + ':' + _cf_run_id_suffix",
        "",
        "# Iceberg catalog configuration for AWS Glue Catalog.",
        "spark.conf.set('spark.sql.catalog.glue_catalog', 'org.apache.iceberg.spark.SparkCatalog')",
        "spark.conf.set('spark.sql.catalog.glue_catalog.catalog-impl', 'org.apache.iceberg.aws.glue.GlueCatalog')",
        "spark.conf.set('spark.sql.catalog.glue_catalog.io-impl', 'org.apache.iceberg.aws.s3.S3FileIO')",
        *_iceberg_warehouse_lines(warehouse),
        "",
    ]


def render_target_namespace_create(
    contract: SemanticContract,
    *,
    environment_parameters: dict[str, object] | None = None,
) -> str:
    """Render target namespace creation for the protected job body."""

    warehouse = resolve_iceberg_warehouse(contract, environment_parameters=environment_parameters)
    return f"spark.sql({render_create_namespace_sql(glue_database_name(contract), warehouse=warehouse)!r})"


def _function_import_lines(contract: SemanticContract) -> list[str]:
    lines: list[str] = []
    if preparation_requires_window(contract):
        lines.append("from pyspark.sql import Window")
    if preparation_requires_functions(contract) or write_requires_functions(contract):
        lines.append("from pyspark.sql import functions as F")
    return lines


def _runtime_import_lines(*, needs_boto3: bool, needs_secret_resolver: bool) -> list[str]:
    lines: list[str] = []
    if needs_boto3:
        lines.append("import boto3")
    if needs_secret_resolver:
        lines.append("import json")
    return lines


def _runtime_helper_lines(*, needs_secret_resolver: bool, needs_rds_iam: bool) -> list[str]:
    lines: list[str] = []
    if needs_secret_resolver:
        lines.extend([render_secret_resolver_helper(), ""])
    if needs_rds_iam:
        lines.extend([render_rds_iam_token_helper(), ""])
    return lines


def _source_helper_lines(source: dict) -> list[str]:
    lines: list[str] = []
    if source_requires_http_fetch(source):
        lines.extend([render_http_file_helper(), ""])
    if source_requires_http_basic_helper(source):
        lines.extend([render_http_basic_auth_helper(), ""])
    if source_requires_rest_helper(source):
        lines.extend([render_rest_api_helper(), ""])
    return lines


def _preparation_helper_lines(contract: SemanticContract) -> list[str]:
    if not preparation_requires_flatten(contract):
        return []
    return [render_flatten_helper(), ""]


def _iceberg_warehouse_lines(warehouse: str | None) -> list[str]:
    if not warehouse:
        return []
    return [f"spark.conf.set('spark.sql.catalog.glue_catalog.warehouse', {warehouse!r})"]
