"""Render Terraform review scaffolds for AWS Glue jobs."""

from __future__ import annotations

from typing import Any

from contractforge_core.semantic import SemanticContract
from contractforge_aws.rendering.deployment import glue_job_definition_payload
from contractforge_aws.rendering.names import glue_database_name


def render_glue_job_terraform(
    contract: SemanticContract,
    *,
    evidence_database_name: str | None = None,
    environment_parameters: dict[str, Any] | None = None,
) -> str:
    job = glue_job_definition_payload(contract, environment_parameters=environment_parameters)
    database = glue_database_name(contract)
    evidence_database = evidence_database_name or f"{database}_ops"
    lines = [
        '# Generated by ContractForge AWS adapter. Review before applying.',
        'terraform { required_providers { aws = { source = "hashicorp/aws" } } }',
        "",
        *_variable("glue_role_arn", "AWS Glue execution role ARN.", job.get("Role")),
        *_variable("script_s3_uri", "S3 URI of the rendered ContractForge Glue job script.", job["Command"]["ScriptLocation"]),
        *_database("target", database),
        *_database("evidence", evidence_database),
        *_job(job),
    ]
    return "\n".join(lines).rstrip() + "\n"


def _variable(name: str, description: str, default: Any) -> list[str]:
    lines = [f'variable "{name}" {{', "  type        = string", f"  description = {_hcl_string(description)}"]
    text = str(default or "")
    if text and "${" not in text:
        lines.append(f"  default     = {_hcl_string(text)}")
    lines.extend(["}", ""])
    return lines


def _database(name: str, database: str) -> list[str]:
    return [
        f'resource "aws_glue_catalog_database" "{name}" {{',
        f"  name = {_hcl_string(database)}",
        "}",
        "",
    ]


def _job(job: dict[str, Any]) -> list[str]:
    return [
        'resource "aws_glue_job" "contractforge" {',
        f"  name              = {_hcl_string(job['Name'])}",
        "  role_arn          = var.glue_role_arn",
        f"  description       = {_hcl_string(job['Description'])}",
        f"  glue_version      = {_hcl_string(job['GlueVersion'])}",
        f"  worker_type       = {_hcl_string(job['WorkerType'])}",
        f"  number_of_workers = {int(job['NumberOfWorkers'])}",
        f"  timeout           = {int(job['Timeout'])}",
        f"  max_retries       = {int(job['MaxRetries'])}",
        "",
        "  command {",
        f"    name            = {_hcl_string(job['Command']['Name'])}",
        "    script_location = var.script_s3_uri",
        f"    python_version  = {_hcl_string(job['Command']['PythonVersion'])}",
        "  }",
        "",
        "  default_arguments = {",
        *_argument_lines(job["DefaultArguments"]),
        "  }",
        "}",
    ]


def _argument_lines(arguments: dict[str, Any]) -> list[str]:
    return [f"    {_hcl_string(str(key))} = {_hcl_string(str(value))}" for key, value in sorted(arguments.items())]


def _hcl_string(value: str) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'
