"""GCP adapter stabilization status."""

from __future__ import annotations

from typing import Any


def gcp_stabilization_report() -> dict[str, Any]:
    """Return the current GCP adapter stabilization decision.

    ``supported_surface_ready`` covers the documented BigQuery batch surface:
    table/view/SQL sources, GCS load jobs, registered BigLake Iceberg table
    reads, public REST/HTTP materialization, authenticated REST/HTTP Secret
    Manager runtime resolution, append/overwrite/explicit-column upsert,
    advanced write-mode review artifacts, opt-in advanced write-mode smoke evidence, advanced write production
    benchmark evidence, SQL quality checks,
    deterministic schema-policy planning artifacts, an opt-in schema-policy
    runtime enforcement hook, deterministic Dataplex DataScan create and
    execution/readback planning artifacts and a live DataScan DQ
    execution/export readback smoke,
    deterministic governance ledger and reconciliation planning artifacts,
    non-mutating governance reconciliation command/readback, governance-ledger evidence write/readback for declared governance intent, core evidence writes,
    neutral OpenLineage control-table evidence, sequential project smoke support,
    operational cost report query planning and the validated governance smokes.
    ``stable_final`` is true for that scoped claim. Raw Iceberg path
    registration has an adapter-owned command/readback surface, but direct raw
    path query execution remains excluded. Native Dataplex lineage/aspect
    execution/readback is included through explicit command paths. Kafka/Dataflow
    provider parity has live Confluent row, DLQ and no-input replay evidence,
    while broader streaming remains review-scoped. Advanced write modes,
    non-Workflows deployment runners, automatic native
    Dataplex lineage/aspect emission, governance auto-repair and overwrite-retention certification
    are explicit exclusions from the first GCP stable surface.
    """

    return {
        "adapter": "contractforge-gcp",
        "subtarget": "gcp_bigquery",
        "classification": "STABLE_SUPPORTED_SURFACE",
        "supported_surface_ready": True,
        "stable_final": True,
        "release_candidate": "next-gcp-stable-surface",
        "gates": _gates(),
        "real_validation_projects": _real_validation_projects(),
        "accepted_review_boundaries": _accepted_review_boundaries(),
        "next_promotion_gates": _next_promotion_gates(),
        "stability_criteria": "docs/specs/gcp-capability-parity.md",
        "evidence_manifest": "docs/reports/gcp-stable-surface-evidence.json",
        "validated": {
            "planner": True,
            "render_bigquery_sql": True,
            "render_gcs_load_job": True,
            "render_evidence_ddl": True,
            "schema_policy_artifact_planning": True,
            "schema_policy_runtime_hook": True,
            "schema_policy_additive_smoke": True,
            "schema_policy_strict_negative_smoke": True,
            "schema_policy_permissive_smoke": True,
            "schema_policy_type_change_negative_smoke": True,
            "schema_policy_sql_source_smoke": True,
            "schema_policy_gcs_source_smoke": True,
            "schema_policy_type_mutation_decision": True,
            "single_contract_csv_smoke": True,
            "single_contract_evidence_writes": True,
            "neutral_openlineage_evidence": True,
            "dataplex_data_quality_artifact_planning": True,
            "dataplex_data_quality_execution_artifact_planning": True,
            "dataplex_data_quality_execution_smoke": True,
            "dataplex_lineage_aspect_artifact_planning": True,
            "dataplex_lineage_aspect_command_surface": True,
            "dataplex_lineage_aspect_execution_smoke": True,
            "dataplex_lineage_aspect_runtime_decision": True,
            "automatic_native_dataplex_lineage_aspect_emission": False,
            "governance_ledger_artifact_planning": True,
            "governance_ledger_evidence_write_readback": True,
            "governance_ledger_reconciliation_artifact_planning": True,
            "governance_ledger_reconciliation_command_surface": True,
            "operational_cost_report_query": True,
            "sequential_project_smoke": True,
            "workflows_project_runner_artifact_planning": True,
            "workflows_execution_plan_artifact": True,
            "workflows_adapter_command_surface": True,
            "workflows_connector_retry_planning": True,
            "workflows_evidence_readback_planning": True,
            "workflows_evidence_readback_command": True,
            "workflows_execution_scoped_readback_templates": True,
            "workflows_runner_evidence_persistence": True,
            "workflows_quality_failed_row_semantics": True,
            "workflows_execution_scoped_evidence_ids": True,
            "workflows_schema_evidence_persistence": True,
            "workflows_cleanup_command_surface": True,
            "workflows_write_failure_run_evidence": True,
            "workflows_target_evidence_cleanup": True,
            "workflows_target_evidence_reset_command": True,
            "workflows_certified_runner_smoke": True,
            "workflows_bigquery_job_polling_planning": True,
            "workflows_runner_deploy_execute_smoke": True,
            "gcs_file_format_smoke": True,
            "explicit_column_upsert_smoke": True,
            "advanced_write_mode_review_artifact_planning": True,
            "advanced_write_mode_opt_in_smoke": True,
            "advanced_write_hashdiff_preflight_smoke": True,
            "advanced_write_hashdiff_production_benchmark": True,
            "advanced_write_hashdiff_cross_adapter_production_parity": True,
            "advanced_write_historical_snapshot_production_benchmark": True,
            "live_bronze_to_gold_e2e": True,
            "row_access_policy_smoke": True,
            "failed_run_evidence_smoke": True,
            "data_masking_policy_smoke": True,
            "annotations_description_smoke": True,
            "policy_tag_access_smoke": True,
            "biglake_iceberg_smoke": True,
            "public_rest_http_source_materialization": True,
            "authenticated_rest_http_secret_manager_review_artifact_planning": True,
            "authenticated_rest_http_secret_manager_execution_smoke": True,
            "authenticated_rest_http_secret_manager_variants_smoke": True,
            "public_http_sources_bigquery_smoke": True,
            "http_file_binary_bigquery_smoke": True,
            "raw_iceberg_registration_command_smoke": True,
            "non_jdbc_source_family_promotion_artifact_planning": True,
            "streaming_scope_decision": True,
            "dataflow_streaming_source_promotion_command_surface": True,
            "streaming_provider_parity": True,
            "write_mode_scope_decision": True,
            "deployment_orchestration_scope_decision": True,
            "dataplex_lineage_dq_scope_decision": True,
            "governance_stable_scope_decision": True,
            "governance_e2e": True,
            "schema_policy_e2e": True,
            "streaming_e2e": True,
        },
    }


def _gates() -> list[dict[str, str]]:
    return [
        {"id": "GCP-BQ-01", "name": "plan and render parity", "status": "PASS"},
        {"id": "GCP-BQ-02", "name": "GCS file format E2E", "status": "PASS"},
        {"id": "GCP-BQ-03", "name": "bronze-to-gold medallion E2E", "status": "PASS"},
        {"id": "GCP-BQ-04", "name": "explicit-column upsert E2E", "status": "PASS"},
        {"id": "GCP-BQ-05", "name": "run, quality and failed-run evidence", "status": "PASS"},
        {"id": "GCP-BQ-07A", "name": "schema policy artifact planning", "status": "PASS"},
        {"id": "GCP-BQ-07B", "name": "schema policy runtime hook", "status": "PASS"},
        {"id": "GCP-BQ-07C", "name": "schema policy additive nullable E2E", "status": "PASS"},
        {"id": "GCP-BQ-07D", "name": "schema policy strict negative E2E", "status": "PASS"},
        {"id": "GCP-BQ-07E", "name": "schema policy permissive nullable E2E", "status": "PASS"},
        {"id": "GCP-BQ-07F", "name": "schema policy destructive type-change negative E2E", "status": "PASS"},
        {"id": "GCP-BQ-07G", "name": "schema policy SQL source E2E", "status": "PASS"},
        {"id": "GCP-BQ-07H", "name": "schema policy GCS load source E2E", "status": "PASS"},
        {"id": "GCP-BQ-07I", "name": "schema policy type mutation decision", "status": "PASS"},
        {"id": "GCP-BQ-07", "name": "schema policy live enforcement", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"id": "GCP-BQ-10", "name": "operational cost report query", "status": "PASS"},
        {"id": "GCP-BQ-11A", "name": "neutral OpenLineage control-table evidence", "status": "PASS"},
        {"id": "GCP-BQ-19", "name": "sequential project smoke runner", "status": "PASS"},
        {"id": "GCP-BQ-08", "name": "governance smokes", "status": "PASS_WITH_REVIEW_BOUNDARIES"},
        {"id": "GCP-BQ-09", "name": "annotation smoke", "status": "PASS"},
        {"id": "GCP-BQ-12", "name": "advanced write mode scope", "status": "EXCLUDED_FROM_STABLE_FINAL"},
        {"id": "GCP-BQ-12B", "name": "advanced write-mode review artifact planning", "status": "PASS"},
        {"id": "GCP-BQ-12A", "name": "advanced write-mode opt-in replay smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"id": "GCP-BQ-12C1", "name": "hash-diff changed-wave and source-key preflight smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"id": "GCP-BQ-12C2", "name": "historical delete-expression and late-arriving reject smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"id": "GCP-BQ-12C3", "name": "snapshot complete-source reactivation and tombstone smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"id": "GCP-BQ-12C4", "name": "hash-diff production benchmark and overlap smoke", "status": "PASS"},
        {"id": "GCP-BQ-12C", "name": "hash-diff cross-adapter production parity", "status": "PASS"},
        {"id": "GCP-BQ-12C5", "name": "historical and snapshot production benchmark", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"id": "GCP-BQ-13", "name": "streaming scope", "status": "EXCLUDED_FROM_STABLE_FINAL"},
        {"id": "GCP-BQ-13A0", "name": "Dataflow Kafka source-promotion command surface", "status": "PASS"},
        {"id": "GCP-BQ-13A", "name": "streaming provider parity", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"id": "GCP-BQ-14", "name": "BigLake Iceberg smoke", "status": "PASS"},
        {"id": "GCP-BQ-15A", "name": "Workflows project runner artifact planning with bounded polling", "status": "PASS"},
        {"id": "GCP-BQ-15B", "name": "Workflows runner live deploy and execute smoke", "status": "PASS"},
        {"id": "GCP-BQ-15C0", "name": "Workflows adapter command surface", "status": "PASS"},
        {"id": "GCP-BQ-15C1", "name": "Workflows connector retry planning", "status": "PASS"},
        {"id": "GCP-BQ-15C2", "name": "Workflows evidence readback planning", "status": "PASS"},
        {"id": "GCP-BQ-15C3", "name": "Workflows evidence readback command", "status": "PASS"},
        {"id": "GCP-BQ-15C4", "name": "Workflows runner evidence persistence", "status": "PASS"},
        {"id": "GCP-BQ-15C5", "name": "Workflows quality failed-row semantics", "status": "PASS"},
        {"id": "GCP-BQ-15C6", "name": "Workflows execution-scoped evidence ids", "status": "PASS"},
        {"id": "GCP-BQ-15C7", "name": "Workflows schema evidence persistence", "status": "PASS"},
        {"id": "GCP-BQ-15C8", "name": "Workflows cleanup command surface", "status": "PASS"},
        {"id": "GCP-BQ-15C9", "name": "Workflows write failure run evidence", "status": "PASS"},
        {"id": "GCP-BQ-15C10", "name": "Workflows target and evidence cleanup", "status": "PASS"},
        {"id": "GCP-BQ-15C", "name": "certified Workflows deployment runner", "status": "PASS"},
        {"id": "GCP-BQ-15", "name": "deployment orchestration scope", "status": "PASS_WITH_NON_WORKFLOWS_EXCLUSIONS"},
        {"id": "GCP-BQ-16A", "name": "Dataplex data-quality artifact planning", "status": "PASS"},
        {"id": "GCP-BQ-16A1", "name": "Dataplex execution/readback artifact planning", "status": "PASS"},
        {"id": "GCP-BQ-16A2", "name": "Dataplex data-quality execution/readback smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"id": "GCP-BQ-16B0", "name": "Dataplex lineage and aspect artifact planning", "status": "PASS"},
        {"id": "GCP-BQ-16B1", "name": "Dataplex lineage and aspect command surface", "status": "PASS"},
        {"id": "GCP-BQ-16B2", "name": "Dataplex lineage and aspect execution/readback smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"id": "GCP-BQ-16B3", "name": "Dataplex lineage and aspect runtime decision", "status": "PASS"},
        {"id": "GCP-BQ-16", "name": "Dataplex lineage and aspects scope", "status": "PASS"},
        {"id": "GCP-BQ-17A", "name": "governance ledger artifact planning", "status": "PASS"},
        {"id": "GCP-BQ-17B1", "name": "governance ledger evidence write/readback", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"id": "GCP-BQ-17B2", "name": "governance ledger reconciliation artifact planning", "status": "PASS"},
        {"id": "GCP-BQ-17B", "name": "governance ledger reconciliation command surface", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"id": "GCP-BQ-17", "name": "governance stable scope", "status": "PASS_WITH_REVIEW_BOUNDARIES"},
        {"id": "GCP-BQ-18", "name": "stable surface manifest", "status": "PASS"},
        {"id": "GCP-BQ-20A", "name": "public REST/HTTP source materialization", "status": "PASS"},
        {"id": "GCP-BQ-20B", "name": "authenticated REST/HTTP Secret Manager review artifact planning", "status": "PASS"},
        {"id": "GCP-BQ-20D", "name": "authenticated REST/HTTP Secret Manager execution smoke", "status": "PASS"},
        {"id": "GCP-BQ-20C", "name": "non-JDBC source-family promotion artifact planning", "status": "PASS"},
        {"id": "GCP-BQ-20E", "name": "raw Iceberg BigLake registration command", "status": "PASS_WITH_REVIEW_BOUNDARY"},
    ]


def _real_validation_projects() -> list[dict[str, str]]:
    return [
        {"name": "gcp_bigquery_csv_smoke", "status": "PASS"},
        {"name": "gcp_bigquery_file_formats_smoke", "status": "PASS"},
        {"name": "gcp_bigquery_upsert_smoke", "status": "PASS"},
        {"name": "gcp_bigquery_bronze_to_gold_smoke", "status": "PASS"},
        {"name": "gcp_bigquery_schema_policy_smoke", "status": "PASS"},
        {"name": "gcp_bigquery_schema_policy_strict_smoke", "status": "PASS_NEGATIVE"},
        {"name": "gcp_bigquery_schema_policy_permissive_smoke", "status": "PASS"},
        {"name": "gcp_bigquery_schema_policy_type_change_smoke", "status": "PASS_NEGATIVE"},
        {"name": "gcp_bigquery_schema_policy_sql_source_smoke", "status": "PASS"},
        {"name": "gcp_bigquery_schema_policy_gcs_source_smoke", "status": "PASS"},
        {"name": "gcp_schema_policy_type_mutation_decision", "status": "DECIDED"},
        {"name": "gcp_bigquery_row_access_policy_smoke", "status": "PASS"},
        {"name": "gcp_bigquery_data_masking_smoke", "status": "PASS"},
        {"name": "gcp_bigquery_policy_tags_smoke", "status": "PASS"},
        {"name": "gcp_bigquery_annotations_smoke", "status": "PASS"},
        {"name": "gcp_governance_ledger_evidence_smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"name": "gcp_governance_ledger_reconciliation_smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"name": "gcp_bigquery_error_evidence_smoke", "status": "PASS"},
        {"name": "gcp_biglake_iceberg_smoke", "status": "PASS"},
        {"name": "gcp_http_sources_bigquery_smoke", "status": "PASS"},
        {"name": "gcp_bigquery_advanced_write_smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"name": "gcp_bigquery_advanced_write_preflight_smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"name": "gcp_bigquery_historical_edge_smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"name": "gcp_bigquery_snapshot_variant_smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"name": "gcp_bigquery_hashdiff_production_benchmark", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"name": "gcp_hashdiff_cross_adapter_production_parity", "status": "PASS"},
        {"name": "gcp_bigquery_advanced_write_production_benchmark", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"name": "gcp_workflows_runner_smoke", "status": "PASS"},
        {"name": "gcp_workflows_command_readback_smoke", "status": "PASS"},
        {"name": "gcp_workflows_runner_evidence_smoke", "status": "PASS"},
        {"name": "gcp_workflows_quality_semantics_smoke", "status": "PASS"},
        {"name": "gcp_workflows_execution_runid_smoke", "status": "PASS"},
        {"name": "gcp_workflows_schema_evidence_smoke", "status": "PASS"},
        {"name": "gcp_workflows_cleanup_command_smoke", "status": "PASS"},
        {"name": "gcp_workflows_write_failure_evidence_smoke", "status": "PASS"},
        {"name": "gcp_workflows_target_evidence_cleanup_smoke", "status": "PASS"},
        {"name": "gcp_workflows_certified_runner_smoke", "status": "PASS"},
        {"name": "gcp_dataplex_data_quality_execution_smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"name": "gcp_dataplex_lineage_aspects_smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"name": "gcp_dataplex_lineage_aspect_runtime_decision", "status": "DECIDED"},
        {"name": "gcp_authenticated_rest_secret_manager_smoke", "status": "PASS"},
        {"name": "gcp_auth_rest_http_secret_manager_variants_smoke", "status": "PASS"},
        {"name": "gcp_http_file_binary_bigquery_smoke", "status": "PASS"},
        {"name": "gcp_raw_iceberg_registration_smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
        {"name": "gcp_confluent_kafka_dataflow_source_promotion_smoke", "status": "PASS_WITH_REVIEW_BOUNDARY"},
    ]


def _accepted_review_boundaries() -> list[dict[str, str]]:
    return [
        {
            "code": "GCP_ADVANCED_WRITE_MODES_REVIEW",
            "area": "hash_diff_upsert, historical and snapshot_reconcile_soft_delete",
            "decision": "HASH_DIFF_PRODUCTION_PARITY_ACCEPTED_HISTORICAL_SNAPSHOT_EXCLUDED",
            "reason": "BigQuery primitives exist, the adapter renders deterministic review artifacts, and opt-in real-account smokes passed compact replay/idempotency checks for hash_diff_upsert, historical and snapshot_reconcile_soft_delete. Follow-up smokes passed hash_diff_upsert changed-row replay, null/duplicate merge-key preflight failures, historical delete-expression expiration, historical late-arriving reject failure, snapshot complete-source blocking, same-hash reactivation, tombstone and replay evidence. GCP, AWS and Snowflake production-sized hash_diff_upsert reports exist and Fabric stable-surface evidence covers seed/no-op/change waves, so the hash-diff production parity decision is accepted. Historical and snapshot cross-adapter production parity remains future work.",
        },
        {
            "code": "GCP_STREAMING_REVIEW",
            "area": "Kafka/Event Hubs/Dataflow/Pub/Sub streaming",
            "decision": "PROVIDER_PARITY_VALIDATED_BROADER_STREAMING_EXCLUDED",
            "reason": "Streaming remains outside the first stable-final default surface, but GCP-BQ-13A is closed for the Confluent/Dataflow provider path. A contract-owned kafka_available_now fixture launched the Google Kafka-to-BigQuery Flex Template, reached JOB_TYPE_STREAMING in us-central1-f, wrote 12 BigQuery rows including a live 3-row batch, read back zero DLQ rows, and a same-consumer-group no-input replay kept the row count unchanged at 12 while the replay job was running. This validates row ingestion, zero-DLQ reconciliation and no-input replay for the provider maturity gate; broader Pub/Sub/Event Hubs and production streaming operations remain review-scoped.",
        },
        {
            "code": "GCP_AUTHENTICATED_REST_HTTP_REVIEW",
            "area": "authenticated REST/HTTP credential boundaries",
            "decision": "PLACEHOLDER_SECRET_MANAGER_EXECUTION_INCLUDED_INLINE_CREDENTIALS_EXCLUDED",
            "reason": "Contracts with {{ secret:scope/key }} placeholders render deterministic Secret Manager resource, IAM and access-command review artifacts and passed live authenticated REST, REST API-key, HTTP JSON bearer-token and HTTP JSON API-key execution through runtime Secret Manager resolution. Inline credentials remain review-required.",
        },
        {
            "code": "GCP_SOURCE_FAMILY_PROMOTION_REVIEW",
            "area": "raw Iceberg path, Delta/Delta Sharing, undeclared/unsupported HTTP file variants and streaming source execution",
            "decision": "RAW_ICEBERG_REGISTRATION_INCLUDED_OTHER_EXECUTION_EXCLUDED",
            "reason": "The adapter emits deterministic source-family promotion plans with required bindings, evidence requirements and blockers for selected non-JDBC review-required sources. Raw Iceberg paths additionally emit and execute BigLake registration plans with Cloud Resource connection/IAM requirements, explicit schema, bq mk flags, readback assertions and post-registration table-source shape. Delta/Delta Sharing sources emit Dataproc Serverless Spark materialization plans with dependency, landing and post-materialization source bindings. Kafka/Event Hubs sources emit Dataflow Kafka-to-BigQuery promotion plans with template parameters, checkpoint, consumer-group and offset evidence requirements. Declared-format http_file and line-oriented http_text have adapter-runtime paths with live BigQuery project-smoke evidence for Avro/CSV/JSON/ORC/Parquet/text. Direct raw Iceberg path queries without registration, Delta/Delta Sharing execution, undeclared/unsupported HTTP file variants and streaming execution remain excluded until real-account E2E evidence exists for each source family.",
        },
        {
            "code": "GCP_DEPLOYMENT_ORCHESTRATION_REVIEW",
            "area": "Workflows, Cloud Run Jobs, Composer DAGs and scheduled-query runners",
            "decision": "WORKFLOWS_INCLUDED_NON_WORKFLOWS_EXCLUDED",
            "reason": "The adapter validates render and smoke execution, generates a deterministic Workflows runner plan with bounded BigQuery job polling, connector retry blocks and broad/execution-scoped evidence-readback queries, exposes adapter-owned deploy/run/wait/readback/reset/cleanup flags, and has live evidence for deploy/execute, command-path readback, runner-side run/quality/schema evidence, quality failed-row semantics, execution-scoped evidence ids, workflow cleanup, write-failure evidence, target/evidence cleanup and repeated full-project rerun execution/readback. Google Workflows is now the certified GCP project deployment runner; Cloud Run Jobs, Composer DAGs and scheduled-query deployment runners remain excluded until separately validated.",
        },
        {
            "code": "GCP_SCHEMA_POLICY_REVIEW",
            "area": "automatic BigQuery type widening or type mutation",
            "decision": "REVIEW_REQUIRED_OUTSIDE_STABLE_RUNTIME",
            "reason": "The adapter renders deterministic BigQuery schema-policy preflight plans and schema evidence DDL, has an opt-in runtime hook for BigQuery table/view/SQL-source and declared-schema GCS load-source inspection, and validated additive_only nullable application, permissive nullable application, strict drift failure, destructive type-change failure, SQL-source schema enforcement and GCS/load-family schema enforcement in real BigQuery smokes. Automatic type widening or mutation remains review-required and is blocked with schema evidence in the stable runtime path.",
        },
        {
            "code": "GCP_DATAPLEX_LINEAGE_DQ_REVIEW",
            "area": "native Dataplex lineage and Knowledge Catalog aspects",
            "decision": "EXPLICIT_COMMAND_SURFACE_INCLUDED_AUTOMATIC_EMISSION_EXCLUDED",
            "reason": "SQL quality and BigQuery evidence are validated, deterministic Dataplex DataScan create plus execution/readback command artifacts exist, and a live native DataScan job exported seven quality-result rows for a 10,000-row target. Deterministic Dataplex Data Lineage publication/readback and governance aspect taxonomy/apply/readback plans are generated from contracts, and the adapter-owned command executed against a real project with run-scoped native lineageEvents readback plus Knowledge Catalog/Dataplex aspect modifyEntry/readback. The stable runtime decision is explicit command execution only; automatic native lineage/aspect emission during every contract run remains excluded because it would add mutating Dataplex API side effects, IAM/quota coupling and retry/idempotency semantics to ordinary contract execution.",
        },
        {
            "code": "GCP_GOVERNANCE_LEDGER_REVIEW",
            "area": "tag-based masking, auto-repair and overwrite retention",
            "decision": "NON_MUTATING_RECONCILIATION_INCLUDED_AUTO_REPAIR_EXCLUDED",
            "reason": "Row access, direct masking, policy-tag column access, descriptions, deterministic governance ledger/reconciliation artifacts, smoke-runtime governance evidence write/readback and the non-mutating governance-reconcile command surface are validated. Automatic repair/deletion, overwrite-retention certification and policy-tag-backed masking remain outside the scoped claim.",
        },
    ]


def _next_promotion_gates() -> list[dict[str, str]]:
    return [
        {
            "id": "GCP-BQ-12D",
            "name": "historical and snapshot production parity",
            "status": "FUTURE",
            "requires": "cross-adapter production-sized parity acceptance for historical and snapshot_reconcile_soft_delete contracts beyond the recorded GCP and Fabric evidence.",
            "evidence": "docs/reports/cross-adapter-production-run-scope-check.json",
        },
        {
            "id": "GCP-BQ-20",
            "name": "expanded source families",
            "status": "FUTURE",
            "requires": "Delta Sharing, direct raw Iceberg path execution without registration, undeclared/unsupported HTTP file variants and other non-JDBC source-family E2E validation without workaround code.",
            "evidence": "docs/specs/gcp-capability-parity.md",
        },
    ]
