"""Official Databricks write-engine parity scenarios."""

from __future__ import annotations

from contractforge_core.parity import ParityMetricExpectation, WriteEngineParityScenario

CLASSIC_AND_SERVERLESS = ("databricks_classic", "databricks_serverless")

WRITE_ENGINE_PARITY_SCENARIOS: tuple[WriteEngineParityScenario, ...] = (
    WriteEngineParityScenario(
        scenario_id="scd1_sql_merge_insert_update",
        title="SCD1 SQL MERGE preserves insert/update semantics",
        write_mode="scd1_upsert",
        candidate_engine="databricks_sql_merge",
        expectation="must_match",
        runtime_targets=CLASSIC_AND_SERVERLESS,
        required_capabilities=("databricks_runtime", "unity_catalog_table", "sql_merge"),
        required_contract_fields=("merge_keys", "transform.deduplicate"),
        expected_semantics=("one current row per merge key", "changed rows update", "new keys insert"),
        metric_expectations=(
            ParityMetricExpectation("rows_inserted", "must match ContractForge Delta"),
            ParityMetricExpectation("rows_updated", "must match ContractForge Delta"),
        ),
    ),
    WriteEngineParityScenario(
        scenario_id="scd1_sql_merge_duplicate_keys",
        title="SCD1 SQL MERGE handles duplicate keys deterministically",
        write_mode="scd1_upsert",
        candidate_engine="databricks_sql_merge",
        expectation="must_match",
        runtime_targets=CLASSIC_AND_SERVERLESS,
        required_capabilities=("databricks_runtime", "unity_catalog_table", "sql_merge"),
        required_contract_fields=("merge_keys", "transform.deduplicate"),
        expected_semantics=("source row selected per key must match ContractForge deduplication",),
        metric_expectations=(ParityMetricExpectation("rows_affected", "must match after deduplication"),),
    ),
    WriteEngineParityScenario(
        scenario_id="scd1_sql_merge_null_keys",
        title="SCD1 SQL MERGE rejects or quarantines null merge keys consistently",
        write_mode="scd1_upsert",
        candidate_engine="databricks_sql_merge",
        expectation="must_match",
        runtime_targets=CLASSIC_AND_SERVERLESS,
        required_capabilities=("databricks_runtime", "unity_catalog_table", "sql_merge"),
        required_contract_fields=("merge_keys", "quality_rules.not_null"),
        expected_semantics=("null merge-key rows follow declared quality behavior",),
        metric_expectations=(ParityMetricExpectation("rows_quarantined", "must match when quarantine is configured"),),
    ),
    WriteEngineParityScenario(
        scenario_id="scd2_auto_cdc_history_lifecycle",
        title="Lakeflow AUTO CDC SCD2 preserves history lifecycle",
        write_mode="scd2_historical",
        candidate_engine="databricks_lakeflow_auto_cdc",
        expectation="must_match",
        runtime_targets=CLASSIC_AND_SERVERLESS,
        required_capabilities=("lakeflow_auto_cdc", "unity_catalog_table"),
        required_contract_fields=("merge_keys", "sequence_by", "scd2_change_columns"),
        expected_semantics=("changed columns expire current row", "new current version is inserted"),
        metric_expectations=(ParityMetricExpectation("rows_expired", "normalized metric must match"),),
    ),
    WriteEngineParityScenario(
        scenario_id="scd2_auto_cdc_late_arriving",
        title="Lakeflow AUTO CDC SCD2 handles late-arriving changes explicitly",
        write_mode="scd2_historical",
        candidate_engine="databricks_lakeflow_auto_cdc",
        expectation="must_match",
        runtime_targets=CLASSIC_AND_SERVERLESS,
        required_capabilities=("lakeflow_auto_cdc", "unity_catalog_table"),
        required_contract_fields=("merge_keys", "sequence_by", "scd2_late_arriving_policy"),
        expected_semantics=("late-arriving records must not corrupt current row",),
        metric_expectations=(ParityMetricExpectation("rows_expired", "must match or document intentional difference"),),
    ),
    WriteEngineParityScenario(
        scenario_id="scd2_auto_cdc_delete_semantics",
        title="Lakeflow AUTO CDC SCD2 delete predicates preserve declared delete behavior",
        write_mode="scd2_historical",
        candidate_engine="databricks_lakeflow_auto_cdc",
        expectation="must_match",
        runtime_targets=CLASSIC_AND_SERVERLESS,
        required_capabilities=("lakeflow_auto_cdc", "unity_catalog_table"),
        required_contract_fields=("merge_keys", "sequence_by", "apply_as_deletes"),
        expected_semantics=("delete predicates must be explicit and reviewed",),
        metric_expectations=(ParityMetricExpectation("rows_deleted", "must match declared delete behavior"),),
    ),
    WriteEngineParityScenario(
        scenario_id="hash_diff_auto_cdc_non_equivalence",
        title="Hash-diff append is not equivalent to Lakeflow SCD type 1",
        write_mode="scd1_hash_diff",
        candidate_engine="databricks_lakeflow_auto_cdc",
        expectation="unsupported",
        runtime_targets=CLASSIC_AND_SERVERLESS,
        required_capabilities=("lakeflow_auto_cdc",),
        required_contract_fields=("hash_keys",),
        expected_semantics=("hash diff appends changed versions; Lakeflow SCD1 stores current state",),
        metric_expectations=(ParityMetricExpectation("rows_inserted", "must not be compared"),),
        blockers_to_record=("scd1_hash_diff is append-only version capture, not Lakeflow SCD type 1.",),
    ),
    WriteEngineParityScenario(
        scenario_id="snapshot_soft_delete_auto_cdc_difference",
        title="Snapshot soft delete differs from AUTO CDC snapshot deletes",
        write_mode="snapshot_soft_delete",
        candidate_engine="databricks_lakeflow_auto_cdc",
        expectation="intentional_difference",
        runtime_targets=CLASSIC_AND_SERVERLESS,
        required_capabilities=("lakeflow_auto_cdc",),
        required_contract_fields=("merge_keys",),
        expected_semantics=("ContractForge marks missing keys inactive; snapshot CDC may delete missing keys",),
        metric_expectations=(ParityMetricExpectation("rows_deleted", "expected to differ"),),
        blockers_to_record=("AUTO CDC snapshot deletes are not inactive-marker soft deletes.",),
    ),
)
