from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def test_fabric_parity_doc_states_render_only_scope_and_maturity_gates() -> None:
    doc = (ROOT / "adapters" / "fabric" / "PARITY.md").read_text(encoding="utf-8")

    required = [
        "ContractForge Fabric Parity Review",
        "It is not a site publication document",
        "Runtime execution | `READ_WRITE_E2E`",
        "REST automation | `PARTIAL_SMOKE`",
        "`00000000-0000-0000-0000-000000000000`",
        "USGS REST/GeoJSON E2E | `READ_WRITE_E2E`",
        "Real E2E evidence | `READ_WRITE_E2E`",
        "docs/reports/fabric-usgs-rest-e2e-smoke.json",
        "docs/reports/fabric-project-deploy-smoke.json",
        "docs/reports/fabric-onelake-data-access-role-smoke.json",
        "docs/reports/fabric-onelake-row-column-policy-smoke.json",
        "docs/reports/fabric-deployment-pipeline-read-probe.json",
        "docs/reports/fabric-deployment-pipeline-lifecycle-smoke.json",
        "docs/reports/fabric-deployment-pipeline-stage-promotion-smoke.json",
        "Spark pool sizing",
        "Spark settings preflight",
        "cf_small_single_node",
        "00000000-0000-0000-0000-000000000000",
        "Microsoft Fabric documentation",
        "Fabric REST API overview",
        "notebook-first Lakehouse execution",
        ".fabric.notebook.py",
        "LRO polling",
        "Retry-After",
        "Capacity preflight",
        "`append`, `overwrite`, `upsert`, `hash_diff_upsert`, `historical`, `snapshot_reconcile_soft_delete`",
        "`fabric_lakehouse_delta_tables`",
        "F4 Bronze-to-gold REST/GeoJSON E2E",
        "F14 Contract parity report",
        "F15 REST hardening",
        "F16 CI/CD model",
        "`text`, `orc`, `avro` and `xml` have live source-expansion evidence",
        "docs/reports/fabric-lakehouse-file-formats-source-smoke.json",
        "docs/reports/fabric-onelake-shortcut-source-smoke.json",
        "docs/reports/fabric-external-azure-blob-shortcut-source-smoke.json",
        "docs/reports/fabric-adls-shortcut-source-smoke.json",
        "docs/reports/fabric-gcs-shortcut-source-smoke.json",
        "docs/reports/fabric-external-s3-shortcut-source-smoke.json",
        "docs/reports/fabric-s3-compatible-shortcut-source-smoke.json",
        "docs/reports/fabric-iceberg-table-shortcut-source-smoke.json",
        "docs/reports/fabric-adls-iceberg-table-shortcut-source-smoke.json",
        "docs/reports/fabric-gcs-iceberg-table-shortcut-source-smoke.json",
        "docs/reports/fabric-confluent-kafka-available-now-source-smoke.json",
        "docs/reports/fabric-eventhubs-kafka-available-now-source-smoke.json",
        "Private-network shortcut variants, managed identity/OAuth",
        ".fabric.source_review.json",
        "redacted source review artifacts with",
        "Runtime preflight and Notebook smoke commands print JSON evidence.",
        "Spark settings preflight reports FTL4/default-pool compatibility",
        "skips unchanged updates by fingerprint",
        "blocks differing or unreadable updates",
        "follows async get-definition operations",
        "list/create Spark pools and patch Spark settings",
        "Fabric SQL smoke succeeded",
        "pre-write schema-policy validation",
        "deterministic `hash_diff_upsert` row-hash merge writes",
        "`historical` SCD2 expire-and-insert merge writes",
        "`snapshot_reconcile_soft_delete` complete-source soft-delete merge writes",
        "extensions.fabric.lock_enabled",
        "idempotent evidence/state table bootstrap before lock acquisition",
        "portable shape blocks before transform, quality, schema policy and writes",
        "portable transform blocks before quality, schema policy and writes",
        "public/no-auth bounded HTTP/REST source reads through shared core readers",
        "Fabric Lakehouse ORC, Avro and XML file source expansion completed live",
        "Fabric internal OneLake shortcut source expansion completed live",
        "Fabric external Azure Blob shortcut source expansion completed live",
        "Fabric ADLS Gen2 shortcut source expansion completed live",
        "Fabric GCS shortcut source expansion completed live",
        "Fabric external Amazon S3 shortcut source expansion completed live",
        "Fabric S3-compatible shortcut source expansion completed live",
        "Fabric Amazon S3 Iceberg table shortcut source expansion completed live",
        "Fabric ADLS Gen2 Iceberg table shortcut source expansion completed live",
        "Fabric GCS Iceberg table shortcut source expansion completed live",
        "Fabric Confluent Kafka available-now source expansion completed live",
        "Fabric Event Hubs Kafka-compatible available-now source expansion completed live",
        "Fabric REST primitives can list/apply workspace role assignments",
        "create/list/delete OneLake data access roles",
        "OneLake data access role APIs with row/column constraints",
        "list deployment pipelines and stages",
        "Fabric access planning can execute explicit `extensions.fabric.access_apply`",
        "Fabric project deployment can render a deterministic `deployment/fabric_project_deployment_manifest.json`",
        "Deployment-pipeline read and create/list/delete lifecycle probes succeeded live with cleanup",
        "Stage-to-stage Notebook content promotion succeeded live with target item verification and cleanup",
        "runtime operations metadata evidence writes",
        "explicit Fabric-native OneLake row/column policies are live-certified",
        "Real Notebook execution can still be blocked by Fabric capacity throttling if Spark pool sizing",
    ]

    for phrase in required:
        assert phrase in doc
