"""Render notebook-first Fabric Lakehouse runtime drafts."""

from __future__ import annotations

import json
from typing import Any

from contractforge_core.connectors import catalog_source_query, catalog_source_table_or_path, file_source_format
from contractforge_core.semantic import SemanticContract
from contractforge_fabric.environment import FabricEnvironment
from contractforge_fabric.evidence import render_notebook_evidence_setup
from contractforge_fabric.naming import target_table_name
from contractforge_fabric.preparation import render_flatten_helper, render_preparation, shape_requires_flatten
from contractforge_fabric.quality import render_quality_gate_statement
from contractforge_fabric.security import contains_secret_placeholder, render_secret_resolver_helper
from contractforge_fabric.contract_extensions import fabric_extensions
from contractforge_fabric.sources import classify_fabric_source
from contractforge_fabric.sources.jdbc import is_fabric_jdbc_source, render_jdbc_source_statement
from contractforge_fabric.sources.notebook import (
    render_http_source_helpers,
    render_http_source_statement,
    source_requires_http_helpers,
)
from contractforge_fabric.sources.object_storage import (
    fabric_object_storage_runtime_path,
    is_fabric_object_storage_source,
    render_object_storage_credential_setup,
    source_with_fabric_runtime_binding,
)
from contractforge_fabric.sources.streams import (
    is_fabric_available_now_stream_source,
    is_fabric_bounded_stream_source,
    render_available_now_stream_source,
    render_bounded_stream_source,
)
from contractforge_fabric.write_modes import render_notebook_write_statement


def render_lakehouse_notebook(contract: SemanticContract, environment: FabricEnvironment) -> str:
    """Render a reviewable Fabric notebook Python draft."""

    source = source_with_fabric_runtime_binding(contract.source.raw or {}, fabric_extensions(contract))
    classification = classify_fabric_source(source)
    if not classification.renderable:
        raise ValueError(f"Fabric notebook rendering is not available for source `{classification.source_type}`")

    return "\n".join(
        [
            "# ContractForge Fabric Lakehouse notebook draft",
            "# Generated by contractforge-fabric. Review before execution.",
            "",
            "from pyspark.sql import functions as F",
            "from pyspark.sql.window import Window",
            "from datetime import date, datetime, timezone",
            "import json",
            "import traceback",
            "import uuid",
            "",
            f"WORKSPACE = {json.dumps(environment.workspace_name or environment.workspace_id or 'UNSPECIFIED')}",
            f"LAKEHOUSE = {json.dumps(environment.lakehouse_name or environment.lakehouse_id or 'UNSPECIFIED')}",
            f"EVIDENCE_SCHEMA = {json.dumps(environment.evidence_schema or 'contractforge')}",
            f"SOURCE_TYPE = {json.dumps(classification.source_type)}",
            f"TARGET_TABLE = {json.dumps(target_table_name(contract))}",
            f"WRITE_MODE = {json.dumps(contract.write.mode)}",
            "",
            render_notebook_evidence_setup(contract),
            "",
            render_secret_resolver_helper(environment) if contains_secret_placeholder(source) else "",
            "",
            render_http_source_helpers() if source_requires_http_helpers(source) else "",
            "",
            render_flatten_helper() if shape_requires_flatten(contract) else "",
            "",
            "_cf_bootstrap_evidence_tables()",
            "try:",
            "    _cf_acquire_lock()",
            _indent(_source_statement(source, classification.source_type)),
            "    _cf_rows_read = df.count()",
            _indent(render_preparation(contract)),
            "",
            _indent(render_quality_gate_statement(contract)),
            "    _cf_validate_schema_policy(dataframe=df)",
            "",
            _indent(render_notebook_write_statement(contract)),
            "    _cf_rows_written = df.count()",
            "    _cf_record_quality_evidence()",
            "    _cf_record_explain_evidence(dataframe=df)",
            "    _cf_record_lineage_evidence(input_dataframe=df, output_dataframe=df, status='SUCCESS')",
            "    _cf_record_state_evidence(dataframe=df)",
            "    _cf_record_schema_change_evidence(dataframe=df)",
            "    _cf_record_source_metadata_evidence(dataframe=df)",
            "    _cf_record_operations_evidence()",
            "    _cf_record_annotations_evidence()",
            "    _cf_record_access_evidence()",
            "    _cf_record_run_evidence('SUCCESS')",
            "except Exception as _cf_error:",
            "    _cf_record_quality_evidence()",
            "    _cf_record_error_evidence(_cf_error)",
            "    _cf_record_run_evidence('FAILED', str(_cf_error))",
            "    raise",
            "finally:",
            "    _cf_release_lock()",
            "",
            "# Run and error evidence rows are generated by this notebook.",
            "# This draft is not a validated production runner until real Fabric E2E evidence exists.",
            "",
        ]
    )


def _source_statement(source: dict[str, Any], source_type: str) -> str:
    if source_requires_http_helpers(source):
        return render_http_source_statement(source)
    if is_fabric_jdbc_source(source):
        return render_jdbc_source_statement(source)
    if is_fabric_available_now_stream_source(source):
        return render_available_now_stream_source(source)
    if is_fabric_bounded_stream_source(source):
        return render_bounded_stream_source(source)
    if source_type == "sql":
        return f"df = spark.sql({json.dumps(catalog_source_query(source))})"
    if source_type in {"table", "delta_table", "iceberg_table", "view"}:
        table = catalog_source_table_or_path(source, table_ref_resolver=_logical_ref_name)
        return f"df = spark.table({json.dumps(table)})"

    source_path = fabric_object_storage_runtime_path(source) if is_fabric_object_storage_source(source) else source.get("path")
    if not source_path:
        raise ValueError("Fabric notebook file source rendering requires source.path")
    fmt = file_source_format(source)
    option_call = "".join(
        f".option({json.dumps(key)}, {json.dumps(value)})" for key, value in _reader_options(source, fmt).items()
    )
    setup = render_object_storage_credential_setup(source)
    read = f"df = spark.read.format({json.dumps(fmt)}){option_call}.load({json.dumps(str(source_path))})"
    return "\n".join(item for item in (setup, read) if item)


def _reader_options(source: dict[str, Any], fmt: str) -> dict[str, str]:
    options = {str(key): str(value) for key, value in (source.get("options") or {}).items() if key != "schema"}
    if fmt == "csv" and "header" not in options:
        options["header"] = "true"
    return options


def _logical_ref_name(ref) -> str:
    return ".".join(part for part in (ref.schema, ref.table) if part)


def _indent(block: str, spaces: int = 4) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line if line else "" for line in block.splitlines())
