"""AI-assisted tools for ContractForge."""

from contractforge_ai.agentic import (
    ContextSnapshot,
    GapPlan,
    GenerationAuditEvent,
    GenerationAuditTrail,
    GenerationPolicyEngine,
    GenerationPolicyFinding,
    GenerationPolicyResult,
    GenerationSignature,
    IntentGenerationRequest,
    IntentGenerationResult,
    IntentSpec,
    ProjectState,
    TransformationPlan,
    TransformationStep,
    analyze_project_state,
    generate_from_intent,
    infer_transformation_plan,
    interpret_intent,
    plan_project_gaps,
)
from contractforge_ai.context import (
    ContextFile,
    KnowledgeChunk,
    KnowledgeIndex,
    KnowledgeSearchResult,
    ProjectContextPackage,
    build_knowledge_index,
    build_project_context_package,
    load_knowledge_index,
    query_knowledge_index,
    save_knowledge_index,
)
from contractforge_ai.connectors import (
    ConnectorIntent,
    connector_aliases,
    connector_details,
    connector_intent,
    connector_message,
    supported_connector_names,
)
from contractforge_ai.enrichment import (
    EnrichmentResult,
    enrich_adapter_validation,
    enrich_control_table_analysis,
    enrich_failure_explanation,
    enrich_project_plan,
    enrich_project_synthesis,
    enrich_review_result,
)
from contractforge_ai.explainers.failure import explain_failure
from contractforge_ai.evaluation import (
    EnrichmentQualityReport,
    evaluate_enrichment_quality,
    evaluate_prompt_cases,
    list_prompt_templates,
    render_prompt,
    validate_model_output,
)
from contractforge_ai.generators.contract import generate_contract_draft
from contractforge_ai.generators.metadata import suggest_metadata
from contractforge_ai.generators.project import (
    generate_aws_glue_iceberg_project,
    generate_classic_pyspark_project,
    generate_contractforge_python_project,
    generate_contractforge_yaml_project,
    generate_databricks_dab_project,
    generate_dbt_project,
    generate_fabric_lakehouse_project,
    generate_gcp_bigquery_project,
    generate_snowflake_sql_warehouse_project,
)
from contractforge_ai.generators.shape import suggest_shape
from contractforge_ai.intelligence import CritiqueFinding, CritiqueReport, TaskRouteRequest, TaskRoutingReport, critique_output, route_task
from contractforge_ai.models import (
    Assumption,
    ContractDraftResult,
    EvidenceItem,
    FailureExplanation,
    Finding,
    MetadataSuggestionResult,
    RequiredDecision,
    ReviewResult,
    ShapeSuggestionResult,
    Suggestion,
    Traceability,
    ValidationResult,
    confidence_level,
)
from contractforge_ai.onboarding import AgentInstructionRequest, generate_agent_instruction_plan
from contractforge_ai.observability import ControlTableAnalysis, ControlTableEvidencePackage, analyze_control_tables
from contractforge_ai.planning import (
    ProjectIntent,
    ProjectPlannerRequest,
    ProjectPlannerResult,
    ProjectRecommendation,
    plan_project_from_intent,
)
from contractforge_ai.projects import (
    ArtifactWriteResult,
    DecisionReport,
    ProjectArtifact,
    ProjectPlan,
    load_project_plan,
    write_project_plan,
)
from contractforge_ai.projects.guided import GuidedProjectRequest, GuidedProjectResult, generate_guided_project
from contractforge_ai.reports import (
    RenderedReport,
    render_guided_project_review,
    render_markdown_report,
    render_operational_analysis_review,
)
from contractforge_ai.reviewers.contract import review_contract
from contractforge_ai.reviewers.architecture import ArchitectureConceptFinding, ArchitectureReview, review_governed_architecture
from contractforge_ai.validation import (
    DeterministicValidationCheck,
    DeterministicValidationReport,
    validate_contract_artifact,
    validate_generated_contract,
    validate_model_artifact,
    validate_project_plan_artifact,
    validate_with_contractforge,
)

__all__ = [
    "Assumption",
    "ArchitectureConceptFinding",
    "ArchitectureReview",
    "ArtifactWriteResult",
    "AgentInstructionRequest",
    "ContextSnapshot",
    "ConnectorIntent",
    "DecisionReport",
    "DeterministicValidationCheck",
    "DeterministicValidationReport",
    "EvidenceItem",
    "EnrichmentResult",
    "EnrichmentQualityReport",
    "FailureExplanation",
    "Finding",
    "GapPlan",
    "GenerationAuditEvent",
    "GenerationAuditTrail",
    "GenerationPolicyEngine",
    "GenerationPolicyFinding",
    "GenerationPolicyResult",
    "GenerationSignature",
    "GuidedProjectRequest",
    "GuidedProjectResult",
    "IntentGenerationRequest",
    "IntentGenerationResult",
    "IntentSpec",
    "KnowledgeChunk",
    "KnowledgeIndex",
    "KnowledgeSearchResult",
    "ProjectArtifact",
    "ProjectState",
    "ProjectIntent",
    "ProjectPlan",
    "ProjectPlannerRequest",
    "ProjectPlannerResult",
    "ProjectRecommendation",
    "RequiredDecision",
    "RenderedReport",
    "ContractDraftResult",
    "ContextFile",
    "ControlTableAnalysis",
    "ControlTableEvidencePackage",
    "CritiqueFinding",
    "CritiqueReport",
    "MetadataSuggestionResult",
    "ProjectContextPackage",
    "ReviewResult",
    "ShapeSuggestionResult",
    "Suggestion",
    "TaskRouteRequest",
    "TaskRoutingReport",
    "Traceability",
    "TransformationPlan",
    "TransformationStep",
    "ValidationResult",
    "analyze_control_tables",
    "analyze_project_state",
    "build_knowledge_index",
    "build_project_context_package",
    "confidence_level",
    "connector_aliases",
    "connector_details",
    "connector_intent",
    "connector_message",
    "critique_output",
    "explain_failure",
    "enrich_adapter_validation",
    "enrich_control_table_analysis",
    "enrich_failure_explanation",
    "enrich_project_plan",
    "enrich_project_synthesis",
    "enrich_review_result",
    "evaluate_prompt_cases",
    "evaluate_enrichment_quality",
    "generate_aws_glue_iceberg_project",
    "generate_contract_draft",
    "generate_classic_pyspark_project",
    "generate_contractforge_python_project",
    "generate_contractforge_yaml_project",
    "generate_databricks_dab_project",
    "generate_dbt_project",
    "generate_fabric_lakehouse_project",
    "generate_guided_project",
    "generate_from_intent",
    "generate_gcp_bigquery_project",
    "generate_agent_instruction_plan",
    "generate_snowflake_sql_warehouse_project",
    "infer_transformation_plan",
    "interpret_intent",
    "review_contract",
    "review_governed_architecture",
    "route_task",
    "suggest_metadata",
    "suggest_shape",
    "supported_connector_names",
    "validate_contract_artifact",
    "validate_generated_contract",
    "validate_model_artifact",
    "validate_model_output",
    "validate_project_plan_artifact",
    "validate_with_contractforge",
    "load_knowledge_index",
    "load_project_plan",
    "list_prompt_templates",
    "plan_project_from_intent",
    "plan_project_gaps",
    "query_knowledge_index",
    "render_prompt",
    "render_guided_project_review",
    "render_markdown_report",
    "render_operational_analysis_review",
    "save_knowledge_index",
    "write_project_plan",
]

__version__ = "0.3.0"
