"""Render Google Workflows project runner planning artifacts."""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from typing import Any

import yaml
from contractforge_gcp.rendering.names import table_prefix


class _WorkflowYamlDumper(yaml.SafeDumper):
    pass


def _represent_workflow_string(dumper: yaml.SafeDumper, data: str) -> yaml.nodes.ScalarNode:
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


_WorkflowYamlDumper.add_representer(str, _represent_workflow_string)


@dataclass(frozen=True)
class GCPWorkflowOperation:
    step_name: str
    operation_name: str
    operation: str
    artifact: str
    body: str
    contract_name: str | None = None
    target_table: str | None = None
    evidence_dataset: str | None = None


@dataclass(frozen=True)
class GCPWorkflowReadbackTarget:
    step_name: str
    contract_name: str
    target_table: str


def render_gcp_workflows_runner_yaml(
    *,
    project_name: str,
    project_id: str,
    operations: tuple[GCPWorkflowOperation, ...],
    poll_max_attempts: int = 30,
    poll_sleep_seconds: int = 10,
    connector_retry_max_retries: int = 5,
    connector_retry_initial_delay_seconds: int = 2,
    connector_retry_max_delay_seconds: int = 60,
    connector_retry_multiplier: int = 2,
) -> str:
    """Render a deterministic Workflows source plan for ordered BigQuery jobs."""

    workflow_steps: list[dict[str, Any]] = [
        {
            "init": {
                "assign": [
                    {"contractforge_project": project_name},
                    {"gcp_project_id": project_id},
                    {"contractforge_run_id": '${"workflows:" + sys.get_env("GOOGLE_CLOUD_WORKFLOW_EXECUTION_ID")}'},
                    {"runner_status": "PLANNED_REVIEW_REQUIRED"},
                    {"poll_max_attempts": poll_max_attempts},
                    {"poll_sleep_seconds": poll_sleep_seconds},
                    {"connector_retry_max_retries": connector_retry_max_retries},
                    {"connector_retry_initial_delay_seconds": connector_retry_initial_delay_seconds},
                    {"connector_retry_max_delay_seconds": connector_retry_max_delay_seconds},
                    {"connector_retry_multiplier": connector_retry_multiplier},
                ]
            }
        }
    ]
    for index, operation in enumerate(operations, start=1):
        workflow_steps.extend(_workflow_steps(index, project_id, operation))
    workflow_steps.append(
        {
            "done": {
                "return": {
                    "status": "CERTIFIED_FOR_STABLE_SURFACE",
                    "project": project_name,
                    "operation_count": len(operations),
                    "wait_polling_included": True,
                    "review_boundary": (
                        "Generated by ContractForge for the certified Workflows deployment, "
                        "execution and evidence readback command path."
                    ),
                }
            }
        }
    )
    return yaml.dump(
        {"main": {"steps": workflow_steps}},
        Dumper=_WorkflowYamlDumper,
        sort_keys=False,
        allow_unicode=False,
        width=4096,
    )


def render_gcp_workflows_runner_manifest(
    *,
    project_name: str,
    project_id: str,
    location: str,
    workflow_name: str,
    operations: tuple[GCPWorkflowOperation, ...],
    workflow_artifact: str = "deployment/gcp_workflows_runner.yaml",
) -> str:
    payload = {
        "kind": "contractforge.gcp.workflows_runner_manifest.v1",
        "adapter": "contractforge-gcp",
        "subtarget": "gcp_bigquery",
        "status": "CERTIFIED_FOR_STABLE_SURFACE",
        "project": project_name,
        "workflow": {
            "name": workflow_name,
            "project_id": project_id,
            "location": location,
            "source_artifact": workflow_artifact,
            "execution_plan_artifact": "deployment/gcp_workflows_execution_plan.json",
            "evidence_readback_artifact": "deployment/gcp_workflows_evidence_readback.json",
            "deploy_hint": (
                f"gcloud workflows deploy {workflow_name} --project={project_id} "
                f"--location={location} --source={workflow_artifact}"
            ),
        },
        "execution": {
            "included": False,
            "reason": (
                "The adapter renders a Workflows source plan with bounded BigQuery job polling. Use the "
                "adapter-owned deploy-project orchestration flags for the certified deployment, execution "
                "and evidence readback path."
            ),
        },
        "wait_polling": {
            "included": True,
            "api": "googleapis.bigquery.v2.jobs.get",
            "timeout_behavior": "raise",
            "error_behavior": "raise BigQuery errorResult.message",
        },
        "retry_policy": {
            "included": True,
            "job_insert_predicate": "http.default_retry_predicate_non_idempotent",
            "job_get_predicate": "http.default_retry_predicate",
            "max_retries": 5,
            "backoff": {"initial_delay": 2, "max_delay": 60, "multiplier": 2},
            "certification_status": "CERTIFIED_FOR_STABLE_SURFACE",
            "reason": (
                "Generated Workflows YAML includes connector retry blocks. The adapter-owned Workflows runner is "
                "certified for the stable BigQuery batch surface through repeated live run/readback evidence."
            ),
        },
        "operation_count": len(operations),
        "operations": [
            {
                "step_name": operation.step_name,
                "operation_name": operation.operation_name,
                "operation": operation.operation,
                "artifact": operation.artifact,
                "workflow_step": _step_id(index, operation),
            }
            for index, operation in enumerate(operations, start=1)
        ],
        "sources": [
            "https://docs.cloud.google.com/workflows/docs/reference/syntax",
            "https://docs.cloud.google.com/workflows/docs/reference/googleapis/bigquery/Overview",
        ],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def render_gcp_workflows_execution_plan(
    *,
    project_name: str,
    project_id: str,
    location: str,
    workflow_name: str,
    workflow_artifact: str = "deployment/gcp_workflows_runner.yaml",
    service_account: str | None = None,
) -> str:
    deploy_command = [
        "gcloud",
        "workflows",
        "deploy",
        workflow_name,
        f"--project={project_id}",
        f"--location={location}",
        f"--source={workflow_artifact}",
        "--format=json",
        "--quiet",
    ]
    if service_account:
        deploy_command.insert(-2, f"--service-account={service_account}")
    cleanup_command = [
        "gcloud",
        "workflows",
        "delete",
        workflow_name,
        f"--project={project_id}",
        f"--location={location}",
        "--quiet",
    ]
    execute_command = [
        "gcloud",
        "workflows",
        "execute",
        workflow_name,
        f"--project={project_id}",
        f"--location={location}",
        "--format=json",
    ]
    payload = {
        "kind": "contractforge.gcp.workflows_execution_plan.v1",
        "adapter": "contractforge-gcp",
        "subtarget": "gcp_bigquery",
        "project": project_name,
        "workflow": {
            "name": workflow_name,
            "project_id": project_id,
            "location": location,
            "source_artifact": workflow_artifact,
            "evidence_readback_artifact": "deployment/gcp_workflows_evidence_readback.json",
        },
        "status": "ADAPTER_COMMAND_SURFACE_AVAILABLE",
        "certification_status": "CERTIFIED_FOR_STABLE_SURFACE",
        "commands": {
            "deploy": deploy_command,
            "cleanup": cleanup_command,
            "execute": execute_command,
            "wait_template": [
                "gcloud",
                "workflows",
                "executions",
                "wait",
                "${execution_id}",
                f"--workflow={workflow_name}",
                f"--project={project_id}",
                f"--location={location}",
                "--format=json",
            ],
            "describe_template": [
                "gcloud",
                "workflows",
                "executions",
                "describe",
                "${execution_id}",
                f"--workflow={workflow_name}",
                f"--project={project_id}",
                f"--location={location}",
                "--format=json",
            ],
        },
        "contractforge_cli": {
            "render": [
                "contractforge-gcp",
                "deploy-project",
                "<project.yaml>",
                "--environment-key",
                "gcp",
                "--dry-run",
                "--render-orchestration",
            ],
            "deploy": [
                "contractforge-gcp",
                "deploy-project",
                "<project.yaml>",
                "--environment-key",
                "gcp",
                "--deploy-orchestration",
            ],
            "deploy_execute_wait": [
                "contractforge-gcp",
                "deploy-project",
                "<project.yaml>",
                "--environment-key",
                "gcp",
                "--deploy-orchestration",
                "--run-orchestration",
                "--wait-orchestration",
            ],
            "deploy_execute_wait_readback": [
                "contractforge-gcp",
                "deploy-project",
                "<project.yaml>",
                "--environment-key",
                "gcp",
                "--deploy-orchestration",
                "--run-orchestration",
                "--wait-orchestration",
                "--readback-orchestration",
            ],
            "reset_deploy_execute_wait_readback": [
                "contractforge-gcp",
                "deploy-project",
                "<project.yaml>",
                "--environment-key",
                "gcp",
                "--reset-orchestration-data",
                "--deploy-orchestration",
                "--run-orchestration",
                "--wait-orchestration",
                "--readback-orchestration",
            ],
            "cleanup": [
                "contractforge-gcp",
                "deploy-project",
                "<project.yaml>",
                "--environment-key",
                "gcp",
                "--cleanup-orchestration",
            ],
            "cleanup_data": [
                "contractforge-gcp",
                "deploy-project",
                "<project.yaml>",
                "--environment-key",
                "gcp",
                "--cleanup-orchestration-data",
            ],
        },
        "required_permissions": [
            "Caller needs Workflows deploy/update permissions for deploy orchestration.",
            "Caller needs Workflows execution permissions for run/wait orchestration.",
            "Caller needs Workflows delete permissions for cleanup orchestration.",
            "Caller needs BigQuery table delete and data update permissions for reset-orchestration-data.",
            "Caller needs BigQuery table delete and data update permissions for cleanup-orchestration-data.",
            "The workflow identity needs BigQuery jobUser plus data permissions on target and evidence datasets.",
        ],
        "promotion_blockers": [
            "Cloud Run Jobs, Composer DAGs and BigQuery scheduled-query runners are not certified by this Workflows plan.",
            "Automatic BigQuery type widening or mutation remains governed by the schema-policy gate, not the deployment-runner gate.",
        ],
        "sources": [
            "https://docs.cloud.google.com/sdk/gcloud/reference/workflows/deploy",
            "https://docs.cloud.google.com/sdk/gcloud/reference/workflows/delete",
            "https://docs.cloud.google.com/sdk/gcloud/reference/workflows/execute",
            "https://docs.cloud.google.com/sdk/gcloud/reference/workflows/executions/wait",
            "https://docs.cloud.google.com/sdk/gcloud/reference/workflows/executions/describe",
        ],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def render_gcp_workflows_evidence_readback_plan(
    *,
    project_name: str,
    project_id: str,
    evidence_dataset: str,
    targets: tuple[GCPWorkflowReadbackTarget, ...],
    location: str | None = None,
) -> str:
    evidence_prefix = table_prefix(project_id, evidence_dataset)
    target_tables = tuple(target.target_table for target in targets if target.target_table)
    contract_names = tuple(target.contract_name for target in targets if target.contract_name)
    payload = {
        "kind": "contractforge.gcp.workflows_evidence_readback_plan.v1",
        "adapter": "contractforge-gcp",
        "subtarget": "gcp_bigquery",
        "project": project_name,
        "status": "PLANNED_REVIEW_REQUIRED",
        "certification_status": "CERTIFIED_FOR_STABLE_SURFACE",
        "evidence": {
            "project_id": project_id,
            "dataset": evidence_dataset,
            "location": location or "US",
            "tables": [
                "contractforge_run_evidence",
                "contractforge_quality_evidence",
                "contractforge_schema_evidence",
                "contractforge_annotation_evidence",
                "contractforge_governance_evidence",
                "contractforge_lineage_evidence",
            ],
        },
        "targets": [
            {
                "step_name": target.step_name,
                "contract_name": target.contract_name,
                "target_table": target.target_table,
            }
            for target in targets
        ],
        "queries": {
            "target_row_counts": _target_row_counts_query(targets),
            "run_evidence_by_target": _run_evidence_query(evidence_prefix, target_tables),
            "quality_evidence_by_contract": _quality_evidence_query(evidence_prefix, contract_names),
            "schema_evidence_by_target": _schema_evidence_query(evidence_prefix, target_tables),
            "evidence_table_presence": _evidence_table_presence_query(project_id, evidence_dataset),
        },
        "execution_scoped_queries": {
            "target_row_counts": _target_row_counts_query(targets),
            "run_evidence_by_target": _run_evidence_query(
                evidence_prefix,
                target_tables,
                execution_id_placeholder="${workflow_execution_id_sql}",
            ),
            "quality_evidence_by_contract": _quality_evidence_query(
                evidence_prefix,
                contract_names,
                execution_id_placeholder="${workflow_execution_id_sql}",
            ),
            "schema_evidence_by_target": _schema_evidence_query(
                evidence_prefix,
                target_tables,
                execution_id_placeholder="${workflow_execution_id_sql}",
            ),
            "evidence_table_presence": _evidence_table_presence_query(project_id, evidence_dataset),
        },
        "acceptance": [
            "Every target table query returns a row count.",
            "contractforge_run_evidence has at least one SUCCEEDED row per target table for the orchestrated run window.",
            "contractforge_quality_evidence has only PASSED rows for quality-enabled contracts.",
            "contractforge_schema_evidence has no unexpected FAILED rows for the orchestrated run window.",
            "When a workflow execution id is provided, evidence readback filters run_id to that execution scope.",
            "All required evidence tables exist in the configured evidence dataset.",
        ],
        "promotion_blockers": [
            "Readback is certified for the adapter-owned Workflows runner and stable BigQuery batch surface.",
            "Non-Workflows orchestration surfaces require separate certification.",
        ],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def render_gcp_workflows_cleanup_plan(
    *,
    project_name: str,
    project_id: str,
    evidence_dataset: str,
    targets: tuple[GCPWorkflowReadbackTarget, ...],
    location: str | None = None,
) -> str:
    evidence_prefix = table_prefix(project_id, evidence_dataset)
    target_tables = tuple(target.target_table for target in targets if target.target_table)
    contract_names = tuple(target.contract_name for target in targets if target.contract_name)
    payload = {
        "kind": "contractforge.gcp.workflows_cleanup_plan.v1",
        "adapter": "contractforge-gcp",
        "subtarget": "gcp_bigquery",
        "project": project_name,
        "status": "PLANNED_REVIEW_REQUIRED",
        "certification_status": "CERTIFIED_FOR_STABLE_SURFACE",
        "evidence": {
            "project_id": project_id,
            "dataset": evidence_dataset,
            "location": location or "US",
        },
        "targets": [
            {
                "step_name": target.step_name,
                "contract_name": target.contract_name,
                "target_table": target.target_table,
            }
            for target in targets
        ],
        "queries": _cleanup_queries(evidence_prefix, targets, target_tables, contract_names),
        "acceptance": [
            "Every generated target-table cleanup statement is scoped to a deployment target table.",
            "Evidence cleanup statements filter by target_table or contract_name from the deployment plan.",
            "No dataset-wide DROP SCHEMA, wildcard table delete or unfiltered evidence DELETE is generated.",
        ],
        "promotion_blockers": [
            "Cleanup SQL is deterministic and adapter-owned for the certified Workflows runner.",
            "Operators can opt in with --reset-orchestration-data before a rerun to start from the generated target/evidence boundary.",
            "Operators must opt in with --cleanup-orchestration-data before target or evidence tables are modified.",
            "Workflow-resource cleanup remains separate from target/evidence cleanup.",
        ],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def workflow_name(project_name: str) -> str:
    value = _slug(f"cf-{project_name}-runner")
    return value[:63].rstrip("-") or "cf-project-runner"


def _workflow_steps(index: int, project_id: str, operation: GCPWorkflowOperation) -> list[dict[str, Any]]:
    step_id = _step_id(index, operation)
    if operation.operation == "QUERY":
        failed_run_steps = _failed_run_evidence_steps(index, step_id, project_id, operation)
        return [
            _query_or_load_job_step(
                step_id,
                project_id,
                {"query": {"query": operation.body, "useLegacySql": False}},
                failed_run_steps=failed_run_steps,
            ),
            *_polling_steps(
                step_id,
                project_id,
                on_error_steps=failed_run_steps,
            ),
            *_evidence_steps(index, step_id, project_id, operation),
        ]
    if operation.operation == "LOAD":
        failed_run_steps = _failed_run_evidence_steps(index, step_id, project_id, operation)
        return [
            _query_or_load_job_step(
                step_id,
                project_id,
                {"load": _load_configuration(operation.body, project_id)},
                failed_run_steps=failed_run_steps,
            ),
            *_polling_steps(
                step_id,
                project_id,
                on_error_steps=failed_run_steps,
            ),
            *_evidence_steps(index, step_id, project_id, operation),
        ]
    if operation.operation == "SCHEMA_EVIDENCE":
        sql = _schema_evidence_insert_sql(project_id, operation, run_id_literal="@run_id")
        return [
            _query_job_step(
                step_id,
                project_id,
                sql,
                query_parameters=[_string_query_parameter("run_id", _workflow_evidence_run_id_expr(operation))],
            ),
            *_polling_steps(step_id, project_id),
        ]
    return [
        {
            step_id: {
                "assign": [
                    {
                        f"{step_id}_review_required": (
                            f"{operation.operation} artifact {operation.artifact} requires adapter-specific review."
                        )
                    }
                ]
            }
        }
    ]


def _evidence_steps(
    index: int,
    step_id: str,
    project_id: str,
    operation: GCPWorkflowOperation,
) -> list[dict[str, Any]]:
    if operation.operation_name in {"write_target", "load_source"}:
        sql = _run_evidence_insert_sql(project_id, operation, run_id_literal="@run_id")
        if sql:
            evidence_operation = GCPWorkflowOperation(
                step_name=operation.step_name,
                operation_name=f"{operation.operation_name}_run_evidence",
                operation="QUERY",
                artifact=f"{operation.artifact}#run_evidence",
                body=sql,
            )
            evidence_step_id = _step_id(index, evidence_operation)
            return [
                _query_job_step(
                    evidence_step_id,
                    project_id,
                    sql,
                    query_parameters=[
                        _string_query_parameter("run_id", _workflow_evidence_run_id_expr(operation))
                    ],
                ),
                *_polling_steps(evidence_step_id, project_id),
            ]
    if operation.operation_name == "quality":
        return _quality_evidence_steps(index, step_id, project_id, operation)
    return []


def _query_or_load_job_step(
    step_id: str,
    project_id: str,
    configuration: dict[str, Any],
    *,
    failed_run_steps: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "try": {
            "call": "googleapis.bigquery.v2.jobs.insert",
            "args": {
                "projectId": project_id,
                "body": {"configuration": configuration},
            },
            "result": f"{step_id}_job",
        },
        "retry": _retry_policy(predicate="http.default_retry_predicate_non_idempotent"),
    }
    if failed_run_steps:
        payload["except"] = {
            "as": "e",
            "steps": _failed_run_exception_steps(step_id, failed_run_steps),
        }
    return {step_id: payload}


def _failed_run_evidence_steps(
    index: int,
    step_id: str,
    project_id: str,
    operation: GCPWorkflowOperation,
) -> list[dict[str, Any]] | None:
    if operation.operation_name not in {"write_target", "load_source"}:
        return None
    sql = _run_evidence_insert_sql(
        project_id,
        operation,
        status="FAILED",
        run_id_literal="@run_id",
        error_message_literal=_sql_string("BigQuery Job failed."),
    )
    if not sql:
        return None
    failed_operation = GCPWorkflowOperation(
        step_name=operation.step_name,
        operation_name=f"{operation.operation_name}_failed_run_evidence",
        operation="QUERY",
        artifact=f"{operation.artifact}#failed_run_evidence",
        body=sql,
    )
    failed_step_id = _step_id(index, failed_operation)
    failed_raise_step = _step_id_with_suffix(step_id, "failed_raise")
    return [
        _query_job_step(
            failed_step_id,
            project_id,
            sql,
            query_parameters=[
                _string_query_parameter("run_id", _workflow_evidence_run_id_expr(operation)),
            ],
        ),
        *_polling_steps(failed_step_id, project_id),
        {failed_raise_step: {"raise": "BigQuery Job failed."}},
    ]


def _failed_run_exception_steps(step_id: str, failed_run_steps: list[dict[str, Any]]) -> list[dict[str, Any]]:
    error_var = f"{step_id}_error_message"
    assign_step = _step_id_with_suffix(step_id, "insert_error")
    return [
        {
            assign_step: {
                "assign": [{error_var: "BigQuery Job failed."}],
                "next": next(iter(failed_run_steps[0])),
            }
        }
    ]


def _query_job_step(
    step_id: str,
    project_id: str,
    sql: str,
    *,
    query_parameters: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    query_config: dict[str, Any] = {"query": sql, "useLegacySql": False}
    if query_parameters:
        query_config["parameterMode"] = "NAMED"
        query_config["queryParameters"] = query_parameters
    return {
        step_id: {
            "try": {
                "call": "googleapis.bigquery.v2.jobs.insert",
                "args": {
                    "projectId": project_id,
                    "body": {"configuration": {"query": query_config}},
                },
                "result": f"{step_id}_job",
            },
            "retry": _retry_policy(predicate="http.default_retry_predicate_non_idempotent"),
        }
    }


def _quality_evidence_steps(
    index: int,
    step_id: str,
    project_id: str,
    operation: GCPWorkflowOperation,
) -> list[dict[str, Any]]:
    if not operation.evidence_dataset or not operation.contract_name:
        return []
    results_step = _step_id_with_suffix(step_id, "results")
    assign_step = _step_id_with_suffix(step_id, "failed_rows")
    check_step = _step_id_with_suffix(step_id, "check")
    failed_raise_step = _step_id_with_suffix(step_id, "failed_raise")
    results_var = f"{step_id}_results"
    failed_rows_var = f"{step_id}_failed_rows"
    failed_operation = GCPWorkflowOperation(
        step_name=operation.step_name,
        operation_name="quality_failed_evidence",
        operation="QUERY",
        artifact=f"{operation.artifact}#quality_failed_evidence",
        body="",
    )
    passed_operation = GCPWorkflowOperation(
        step_name=operation.step_name,
        operation_name="quality_passed_evidence",
        operation="QUERY",
        artifact=f"{operation.artifact}#quality_passed_evidence",
        body="",
    )
    failed_step_id = _step_id(index, failed_operation)
    passed_step_id = _step_id(index, passed_operation)
    failed_sql = _quality_evidence_insert_sql(
        project_id,
        operation,
        status="FAILED",
        run_id_literal="@run_id",
        failed_rows_literal="@failed_rows",
    )
    passed_sql = _quality_evidence_insert_sql(
        project_id,
        operation,
        status="PASSED",
        run_id_literal="@run_id",
        failed_rows_literal="0",
    )
    failed_query_parameters = [
        _string_query_parameter("run_id", _workflow_evidence_run_id_expr(operation)),
        {
            "name": "failed_rows",
            "parameterType": {"type": "INT64"},
            "parameterValue": {"value": f"${{string({failed_rows_var})}}"},
        }
    ]
    passed_query_parameters = [_string_query_parameter("run_id", _workflow_evidence_run_id_expr(operation))]
    return [
        {
            results_step: {
                "call": "googleapis.bigquery.v2.jobs.getQueryResults",
                "args": {
                    "projectId": project_id,
                    "jobId": f"${{{step_id}_job.jobReference.jobId}}",
                    "location": f"${{{step_id}_job.jobReference.location}}",
                },
                "result": results_var,
            }
        },
        {assign_step: {"assign": [{failed_rows_var: f"${{int({results_var}.rows[0].f[0].v)}}"}]}},
        {
            check_step: {
                "switch": [{"condition": f"${{{failed_rows_var} > 0}}", "next": failed_step_id}],
                "next": passed_step_id,
            }
        },
        _query_job_step(failed_step_id, project_id, failed_sql, query_parameters=failed_query_parameters),
        *_polling_steps(failed_step_id, project_id),
        {failed_raise_step: {"raise": f'${{"Quality check failed with " + string({failed_rows_var}) + " failed rows."}}'}},
        _query_job_step(passed_step_id, project_id, passed_sql, query_parameters=passed_query_parameters),
        *_polling_steps(passed_step_id, project_id),
    ]


def _polling_steps(
    step_id: str,
    project_id: str,
    *,
    on_error_steps: list[dict[str, Any]] | None = None,
) -> list[dict[str, Any]]:
    poll_init = _step_id_with_suffix(step_id, "poll_init")
    poll_get = _step_id_with_suffix(step_id, "poll_get")
    poll_check = _step_id_with_suffix(step_id, "poll_check")
    poll_error = _step_id_with_suffix(step_id, "poll_error")
    poll_sleep = _step_id_with_suffix(step_id, "poll_sleep")
    poll_timeout = _step_id_with_suffix(step_id, "poll_timeout")
    poll_done = _step_id_with_suffix(step_id, "poll_done")
    attempt_var = f"{step_id}_attempt"
    status_var = f"{step_id}_status"
    error_var = f"{step_id}_error_message"
    if on_error_steps:
        poll_error_steps = [
            {
                poll_error: {
                    "assign": [{error_var: "BigQuery Job failed."}],
                    "next": next(iter(on_error_steps[0])),
                }
            },
            *on_error_steps,
        ]
    else:
        poll_error_steps = [{poll_error: {"raise": f"${{{status_var}.status.errorResult.message}}"}}]
    return [
        {poll_init: {"assign": [{attempt_var: 0}]}},
        {
            poll_get: {
                "try": {
                    "call": "googleapis.bigquery.v2.jobs.get",
                    "args": {
                        "projectId": project_id,
                        "jobId": f"${{{step_id}_job.jobReference.jobId}}",
                        "location": f"${{{step_id}_job.jobReference.location}}",
                    },
                    "result": status_var,
                },
                "retry": _retry_policy(predicate="http.default_retry_predicate"),
            }
        },
        {
            poll_check: {
                "switch": [
                    {
                        "condition": f'${{{status_var}.status.state == "DONE" and "errorResult" in {status_var}.status}}',
                        "next": poll_error,
                    },
                    {
                        "condition": f'${{{status_var}.status.state == "DONE"}}',
                        "next": poll_done,
                    },
                    {
                        "condition": f"${{{attempt_var} >= poll_max_attempts}}",
                        "next": poll_timeout,
                    },
                ],
                "next": poll_sleep,
            }
        },
        *poll_error_steps,
        {poll_timeout: {"raise": f"BigQuery job {step_id} did not finish before poll_max_attempts."}},
        {
            poll_sleep: {
                "assign": [{attempt_var: f"${{{attempt_var} + 1}}"}],
                "next": _step_id_with_suffix(step_id, "sleep_call"),
            }
        },
        {
            _step_id_with_suffix(step_id, "sleep_call"): {
                "call": "sys.sleep",
                "args": {"seconds": "${poll_sleep_seconds}"},
                "next": poll_get,
            }
        },
        {poll_done: {"assign": [{f"{step_id}_final_state": f"${{{status_var}.status.state}}"}]}},
    ]


def _retry_policy(*, predicate: str) -> dict[str, Any]:
    return {
        "predicate": f"${{{predicate}}}",
        "max_retries": "${connector_retry_max_retries}",
        "backoff": {
            "initial_delay": "${connector_retry_initial_delay_seconds}",
            "max_delay": "${connector_retry_max_delay_seconds}",
            "multiplier": "${connector_retry_multiplier}",
        },
    }


def _target_row_counts_query(targets: tuple[GCPWorkflowReadbackTarget, ...]) -> str:
    selects = [
        (
            f"SELECT {_sql_string(target.step_name)} AS step_name, "
            f"{_sql_string(target.target_table)} AS target_table, COUNT(*) AS row_count "
            f"FROM `{target.target_table}`"
        )
        for target in targets
        if target.target_table
    ]
    if not selects:
        return "SELECT 'NO_TARGETS' AS step_name, 'NO_TARGETS' AS target_table, 0 AS row_count;"
    return "\nUNION ALL\n".join(selects) + "\nORDER BY step_name;"


def _run_evidence_query(
    evidence_prefix: str,
    target_tables: tuple[str, ...],
    *,
    execution_id_placeholder: str | None = None,
) -> str:
    filters = [f"target_table IN ({_sql_in_list(target_tables)})"]
    if execution_id_placeholder:
        filters.append(f"run_id LIKE CONCAT('workflows:', {execution_id_placeholder}, ':%')")
    return "\n".join(
        [
            "SELECT",
            "  target_table,",
            "  COUNT(*) AS run_rows,",
            "  COUNTIF(status = 'SUCCEEDED') AS succeeded_rows,",
            "  COUNTIF(status = 'FAILED') AS failed_rows,",
            "  MAX(finished_at) AS last_finished_at",
            f"FROM `{evidence_prefix}.contractforge_run_evidence`",
            "WHERE " + "\n  AND ".join(filters),
            "GROUP BY target_table",
            "ORDER BY target_table;",
        ]
    )


def _quality_evidence_query(
    evidence_prefix: str,
    contract_names: tuple[str, ...],
    *,
    execution_id_placeholder: str | None = None,
) -> str:
    filters = [f"contract_name IN ({_sql_in_list(contract_names)})"]
    if execution_id_placeholder:
        filters.append(f"run_id LIKE CONCAT('workflows:', {execution_id_placeholder}, ':%')")
    return "\n".join(
        [
            "SELECT",
            "  contract_name,",
            "  COUNT(*) AS quality_rows,",
            "  COUNTIF(status = 'PASSED') AS passed_rows,",
            "  COUNTIF(status = 'FAILED') AS failed_rows,",
            "  MAX(evaluated_at) AS last_evaluated_at",
            f"FROM `{evidence_prefix}.contractforge_quality_evidence`",
            "WHERE " + "\n  AND ".join(filters),
            "GROUP BY contract_name",
            "ORDER BY contract_name;",
        ]
    )


def _schema_evidence_query(
    evidence_prefix: str,
    target_tables: tuple[str, ...],
    *,
    execution_id_placeholder: str | None = None,
) -> str:
    filters = [f"target_table IN ({_sql_in_list(target_tables)})"]
    if execution_id_placeholder:
        filters.append(f"run_id LIKE CONCAT('workflows:', {execution_id_placeholder}, ':%')")
    return "\n".join(
        [
            "SELECT",
            "  target_table,",
            "  COUNT(*) AS schema_rows,",
            "  COUNTIF(status = 'SUCCEEDED') AS succeeded_rows,",
            "  COUNTIF(status = 'FAILED') AS failed_rows,",
            "  MAX(evaluated_at) AS last_evaluated_at",
            f"FROM `{evidence_prefix}.contractforge_schema_evidence`",
            "WHERE " + "\n  AND ".join(filters),
            "GROUP BY target_table",
            "ORDER BY target_table;",
        ]
    )


def _evidence_table_presence_query(project_id: str, evidence_dataset: str) -> str:
    return "\n".join(
        [
            "SELECT table_name",
            f"FROM `{project_id}.{evidence_dataset}.INFORMATION_SCHEMA.TABLES`",
            "WHERE table_name IN (",
            "  'contractforge_run_evidence',",
            "  'contractforge_quality_evidence',",
            "  'contractforge_schema_evidence',",
            "  'contractforge_annotation_evidence',",
            "  'contractforge_governance_evidence',",
            "  'contractforge_lineage_evidence'",
            ")",
            "ORDER BY table_name;",
        ]
    )


def _cleanup_queries(
    evidence_prefix: str,
    targets: tuple[GCPWorkflowReadbackTarget, ...],
    target_tables: tuple[str, ...],
    contract_names: tuple[str, ...],
) -> dict[str, str]:
    queries: dict[str, str] = {}
    seen_targets: set[str] = set()
    for target in targets:
        if not target.target_table or target.target_table in seen_targets:
            continue
        seen_targets.add(target.target_table)
        queries[f"01_drop_target_{_cleanup_query_key(target.step_name)}"] = (
            f"DROP TABLE IF EXISTS `{target.target_table}`;"
        )
    if target_tables:
        target_filter = _sql_in_list(target_tables)
        queries["02_delete_run_evidence_by_target"] = (
            f"DELETE FROM `{evidence_prefix}.contractforge_run_evidence` WHERE target_table IN ({target_filter});"
        )
        queries["03_delete_schema_evidence_by_target"] = (
            f"DELETE FROM `{evidence_prefix}.contractforge_schema_evidence` WHERE target_table IN ({target_filter});"
        )
        queries["04_delete_annotation_evidence_by_target"] = (
            f"DELETE FROM `{evidence_prefix}.contractforge_annotation_evidence` WHERE target_table IN ({target_filter});"
        )
        queries["05_delete_governance_evidence_by_target"] = (
            f"DELETE FROM `{evidence_prefix}.contractforge_governance_evidence` WHERE target_table IN ({target_filter});"
        )
        queries["06_delete_lineage_evidence_by_target"] = (
            f"DELETE FROM `{evidence_prefix}.contractforge_lineage_evidence` WHERE target_table IN ({target_filter});"
        )
    if contract_names:
        contract_filter = _sql_in_list(contract_names)
        queries["07_delete_quality_evidence_by_contract"] = (
            f"DELETE FROM `{evidence_prefix}.contractforge_quality_evidence` WHERE contract_name IN ({contract_filter});"
        )
    return queries


def _cleanup_query_key(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").lower() or "target"


def _sql_in_list(values: tuple[str, ...]) -> str:
    if not values:
        return "''"
    return ", ".join(_sql_string(value) for value in values)


def _sql_string(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _run_evidence_insert_sql(
    project_id: str,
    operation: GCPWorkflowOperation,
    *,
    run_id_literal: str | None = None,
    status: str = "SUCCEEDED",
    error_message_literal: str | None = None,
) -> str | None:
    if not operation.evidence_dataset or not operation.target_table or not operation.contract_name:
        return None
    evidence_prefix = table_prefix(project_id, operation.evidence_dataset)
    run_id = f"workflows:{operation.step_name}:{operation.operation_name}"
    statement_type = "LOAD" if operation.operation_name == "load_source" else "QUERY"
    return "\n".join(
        [
            f"INSERT INTO `{evidence_prefix}.contractforge_run_evidence` (",
            "  run_id, contract_name, target_table, adapter, status, started_at, finished_at,",
            "  total_bytes_processed, total_bytes_billed, total_slot_ms, job_id, statement_type,",
            "  inserted_rows, updated_rows, deleted_rows, error_message",
            ") VALUES (",
            f"  {run_id_literal or _sql_string(run_id)},",
            f"  {_sql_string(operation.contract_name)},",
            f"  {_sql_string(operation.target_table)},",
            "  'contractforge-gcp-workflows',",
            f"  {_sql_string(status)},",
            "  CURRENT_TIMESTAMP(),",
            "  CURRENT_TIMESTAMP(),",
            "  NULL, NULL, NULL, NULL,",
            f"  {_sql_string(statement_type)},",
            f"  NULL, NULL, NULL, {error_message_literal or 'NULL'}",
            ");",
        ]
    )


def _quality_evidence_insert_sql(
    project_id: str,
    operation: GCPWorkflowOperation,
    *,
    status: str,
    run_id_literal: str | None = None,
    failed_rows_literal: str | None = None,
) -> str:
    if not operation.evidence_dataset or not operation.contract_name:
        raise ValueError("quality evidence requires evidence_dataset and contract_name")
    evidence_prefix = table_prefix(project_id, operation.evidence_dataset)
    run_id = f"workflows:{operation.step_name}:quality"
    prefix = "\n".join(
        [
            f"INSERT INTO `{evidence_prefix}.contractforge_quality_evidence` (",
            "  run_id, contract_name, rule_name, rule_type, status, failed_rows, evaluated_at",
            ") VALUES (",
            f"  {run_id_literal or _sql_string(run_id)},",
            f"  {_sql_string(operation.contract_name)},",
            f"  {_sql_string(operation.step_name + '_quality')},",
            "  'workflow_quality_query',",
            f"  {_sql_string(status)},",
        ]
    )
    suffix = "\n".join(
        [
            "  CURRENT_TIMESTAMP()",
            ");",
        ]
    )
    return "\n".join(
        [
            prefix,
            f"  {failed_rows_literal or '0'},",
            suffix,
        ]
    )


def _schema_evidence_insert_sql(
    project_id: str,
    operation: GCPWorkflowOperation,
    *,
    run_id_literal: str | None = None,
) -> str:
    if not operation.evidence_dataset or not operation.contract_name or not operation.target_table:
        raise ValueError("schema evidence requires evidence_dataset, contract_name and target_table")
    payload = json.loads(operation.body)
    policy = payload.get("policy") if isinstance(payload.get("policy"), dict) else {}
    schema_policy = str(policy.get("policy") or "unknown")
    schema_changes = {
        "source": "gcp_workflows_schema_policy_plan",
        "status": "planned_no_runtime_drift",
        "artifact": operation.artifact,
        "policy": schema_policy,
    }
    evidence_prefix = table_prefix(project_id, operation.evidence_dataset)
    return "\n".join(
        [
            f"INSERT INTO `{evidence_prefix}.contractforge_schema_evidence` (",
            "  run_id, contract_name, target_table, schema_policy, status, added_columns,",
            "  removed_columns, type_changes_json, schema_changes_json, evaluated_at, error_message",
            ") VALUES (",
            f"  {run_id_literal or _sql_string(f'workflows:{operation.step_name}:schema_evidence')},",
            f"  {_sql_string(operation.contract_name)},",
            f"  {_sql_string(operation.target_table)},",
            f"  {_sql_string(schema_policy)},",
            "  'SUCCEEDED',",
            "  ARRAY<STRING>[],",
            "  ARRAY<STRING>[],",
            "  '[]',",
            f"  {_sql_string(json.dumps(schema_changes, sort_keys=True))},",
            "  CURRENT_TIMESTAMP(),",
            "  NULL",
            ");",
        ]
    )


def _workflow_evidence_run_id_expr(operation: GCPWorkflowOperation) -> str:
    suffix = f"{operation.step_name}:{operation.operation_name}"
    return f'${{contractforge_run_id + ":{suffix}"}}'


def _string_query_parameter(name: str, value: str) -> dict[str, Any]:
    return {
        "name": name,
        "parameterType": {"type": "STRING"},
        "parameterValue": {"value": value},
    }


def _load_configuration(body: str, project_id: str) -> dict[str, Any]:
    payload = json.loads(body)
    destination = _destination_table(str(payload["destination_table"]), project_id)
    config: dict[str, Any] = {
        "sourceUris": list(payload["source_uris"]),
        "destinationTable": destination,
        "sourceFormat": payload["source_format"],
        "writeDisposition": payload["write_disposition"],
    }
    if "autodetect" in payload:
        config["autodetect"] = bool(payload["autodetect"])
    if "skip_leading_rows" in payload:
        config["skipLeadingRows"] = int(payload["skip_leading_rows"])
    if "schema_fields" in payload:
        config["schema"] = {"fields": list(payload["schema_fields"])}
    return config


def _destination_table(ref: str, default_project_id: str) -> dict[str, str]:
    parts = ref.split(".")
    if len(parts) == 3:
        project_id, dataset_id, table_id = parts
    elif len(parts) == 2:
        project_id = default_project_id
        dataset_id, table_id = parts
    else:
        raise ValueError(f"BigQuery destination table must be dataset.table or project.dataset.table: {ref}")
    return {"projectId": project_id, "datasetId": dataset_id, "tableId": table_id}


def _step_id(index: int, operation: GCPWorkflowOperation) -> str:
    return _identifier(f"{index:03d}_{operation.step_name}_{operation.operation_name}")


def _step_id_with_suffix(step_id: str, suffix: str) -> str:
    candidate = f"{step_id}_{suffix}"
    if len(candidate) <= 63:
        return _identifier(candidate)
    digest = hashlib.sha1(candidate.encode("utf-8")).hexdigest()[:8]
    max_base = 63 - len(suffix) - len(digest) - 2
    base = step_id[:max_base].rstrip("_")
    return _identifier(f"{base}_{digest}_{suffix}")


def _identifier(value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9_]+", "_", value)
    normalized = re.sub(r"_+", "_", normalized).strip("_")
    if not normalized or not normalized[0].isalpha():
        normalized = f"step_{normalized}"
    if len(normalized) <= 63:
        return normalized
    digest = hashlib.sha1(normalized.encode("utf-8")).hexdigest()[:8]
    base = normalized[: 63 - len(digest) - 1].rstrip("_")
    return f"{base}_{digest}"


def _slug(value: str) -> str:
    lowered = value.lower().replace("_", "-")
    cleaned = re.sub(r"[^a-z0-9-]+", "-", lowered)
    cleaned = re.sub(r"-+", "-", cleaned).strip("-")
    if not cleaned or not cleaned[0].isalpha():
        cleaned = f"cf-{cleaned}"
    return cleaned
