"""Render Fabric notebook runtime evidence helpers."""

from __future__ import annotations

import json

from contractforge_core.config import CONTROL_COLUMNS
from contractforge_core.connectors import source_metadata_from_contract
from contractforge_core.semantic import SemanticContract
from contractforge_fabric.contract_extensions import fabric_bool, fabric_extensions
from contractforge_fabric.evidence.ddl import render_create_evidence_tables_sql
from contractforge_fabric.naming import openlineage_namespace, source_display_name, target_table_name
from contractforge_fabric.state import render_create_state_tables_sql
from contractforge_fabric.state import notebook_state_lock_options, notebook_state_watermark_column

_IGNORED_TARGET_ONLY_COLUMNS = sorted(
    set(CONTROL_COLUMNS) | {"ingestion_date", "source_system", "ingestion_sequence"}
)


def render_notebook_evidence_setup(contract: SemanticContract) -> str:
    """Render helper functions for Fabric Lakehouse evidence writes."""

    from contractforge_fabric.access import access_steps, has_access_intent
    from contractforge_fabric.annotations import annotation_steps, has_annotations
    from contractforge_fabric.operations import has_operations_metadata, operations_payload

    source_name = source_display_name(contract)
    target = target_table_name(contract)
    namespace = openlineage_namespace(contract)
    job_name = f"{contract.target.layer}.{contract.target.name}.{contract.write.mode}"
    watermark_column = notebook_state_watermark_column(contract)
    lock_options = notebook_state_lock_options(contract)
    extensions = fabric_extensions(contract)
    allow_type_widening = fabric_bool(extensions.get("allow_type_widening", False))
    bootstrap_evidence = fabric_bool(extensions.get("bootstrap_evidence_tables", True))
    source_metadata = source_metadata_from_contract(contract, target_table=target)
    operations = operations_payload(contract) if has_operations_metadata(contract) else {}
    annotations = annotation_steps(contract) if has_annotations(contract) else []
    access = access_steps(contract) if has_access_intent(contract) else []
    bootstrap_sql = _bootstrap_statements() if bootstrap_evidence else []
    return "\n".join(
        [
            "# ContractForge runtime evidence helpers.",
            "RUN_ID = str(uuid.uuid4())",
            f"_CF_LINEAGE_NAMESPACE = {json.dumps(namespace)}",
            f"_CF_LINEAGE_JOB_NAME = {json.dumps(job_name)}",
            f"_CF_LINEAGE_SOURCE_NAME = {json.dumps(source_name)}",
            f"_CF_LINEAGE_TARGET_NAME = {json.dumps(target)}",
            f"_CF_STATE_WATERMARK_COLUMN = {watermark_column!r}",
            f"_CF_LOCK_ENABLED = {bool(lock_options['enabled'])!r}",
            f"_CF_LOCK_OWNER = {lock_options['owner']!r}",
            f"_CF_LOCK_TTL_MINUTES = {int(lock_options['ttl_minutes'])!r}",
            f"_CF_SCHEMA_POLICY = {json.dumps(contract.write.schema_policy)}",
            f"_CF_ALLOW_TYPE_WIDENING = {allow_type_widening!r}",
            f"_CF_EVIDENCE_BOOTSTRAP_ENABLED = {bootstrap_evidence!r}",
            f"_CF_IGNORED_TARGET_ONLY_COLUMNS = set({json.dumps(_IGNORED_TARGET_ONLY_COLUMNS)})",
            f"_CF_SOURCE_METADATA = json.loads({json.dumps(json.dumps(source_metadata, sort_keys=True, separators=(',', ':')))})",
            f"_CF_OPERATIONS_PAYLOAD = json.loads({json.dumps(json.dumps(operations, sort_keys=True, separators=(',', ':')))})",
            f"_CF_ANNOTATION_STEPS = json.loads({json.dumps(json.dumps(annotations, sort_keys=True, separators=(',', ':')))})",
            f"_CF_ACCESS_STEPS = json.loads({json.dumps(json.dumps(access, sort_keys=True, separators=(',', ':')))})",
            f"_CF_EVIDENCE_BOOTSTRAP_SQL = json.loads({json.dumps(json.dumps(bootstrap_sql, sort_keys=True, separators=(',', ':')))})",
            "_cf_started_at_utc = datetime.now(timezone.utc)",
            "_cf_rows_read = 0",
            "_cf_rows_written = 0",
            "_cf_rows_quarantined = 0",
            "_cf_quality_status = 'NOT_CONFIGURED'",
            "_cf_quality_results = []",
            "_cf_quality_evidence_recorded = False",
            "_cf_lineage_evidence_recorded = False",
            "_cf_state_evidence_recorded = False",
            "_cf_source_metadata_evidence_recorded = False",
            "_cf_schema_change_evidence_recorded = False",
            "_cf_explain_evidence_recorded = False",
            "_cf_operations_evidence_recorded = False",
            "_cf_annotations_evidence_recorded = False",
            "_cf_access_evidence_recorded = False",
            "_cf_lock_acquired = False",
            "_cf_schema_lookup_warning = None",
            "_cf_schema_changes = {}",
            "",
            "def _cf_now():",
            "    return datetime.now(timezone.utc)",
            "",
            "def _cf_sql_identifier(value):",
            "    return '`' + str(value).replace('`', '``') + '`'",
            "",
            "def _cf_sql_table(schema, table):",
            "    return f'{_cf_sql_identifier(schema)}.{_cf_sql_identifier(table)}'",
            "",
            "def _cf_sql_literal(value):",
            "    if value is None:",
            "        return 'NULL'",
            "    if isinstance(value, bool):",
            "        return 'TRUE' if value else 'FALSE'",
            "    if isinstance(value, int):",
            "        return str(value)",
            "    if isinstance(value, float):",
            "        return str(value)",
            "    if isinstance(value, datetime):",
            "        return \"TIMESTAMP '\" + value.strftime('%Y-%m-%d %H:%M:%S') + \"'\"",
            "    if isinstance(value, date):",
            "        return \"DATE '\" + value.strftime('%Y-%m-%d') + \"'\"",
            "    return \"'\" + str(value).replace(\"'\", \"''\") + \"'\"",
            "",
            "def _cf_insert_evidence(table, values):",
            "    columns = ', '.join(_cf_sql_identifier(column) for column in values)",
            "    literals = ', '.join(_cf_sql_literal(value) for value in values.values())",
            "    spark.sql(f'INSERT INTO {_cf_sql_table(EVIDENCE_SCHEMA, table)} ({columns}) VALUES ({literals})')",
            "",
            "def _cf_bootstrap_evidence_tables():",
            "    if not _CF_EVIDENCE_BOOTSTRAP_ENABLED:",
            "        return",
            "    for statement in _CF_EVIDENCE_BOOTSTRAP_SQL:",
            "        spark.sql(statement.replace('`__CF_EVIDENCE_SCHEMA__`', _cf_sql_identifier(EVIDENCE_SCHEMA)))",
            "",
            "def _cf_schema_map(dataframe):",
            "    if dataframe is None:",
            "        return {}",
            "    return {field.name: field.dataType.simpleString() for field in dataframe.schema.fields}",
            "",
            "def _cf_decimal_parts(dtype):",
            "    normalized = str(dtype).strip().lower()",
            "    if not normalized.startswith('decimal(') or not normalized.endswith(')'):",
            "        return None",
            "    parts = normalized[len('decimal('):-1].split(',', 1)",
            "    if len(parts) != 2:",
            "        return None",
            "    try:",
            "        return int(parts[0]), int(parts[1])",
            "    except ValueError:",
            "        return None",
            "",
            "def _cf_is_type_widening(source_type, target_type):",
            "    source = str(source_type).strip().lower()",
            "    target = str(target_type).strip().lower()",
            "    if source == target:",
            "        return True",
            "    integer_order = {'tinyint': 0, 'smallint': 1, 'int': 2, 'bigint': 3}",
            "    float_order = {'float': 0, 'double': 1}",
            "    if source in integer_order and target in integer_order:",
            "        return integer_order[source] >= integer_order[target]",
            "    if source in float_order and target in float_order:",
            "        return float_order[source] >= float_order[target]",
            "    if source == 'double' and target in integer_order:",
            "        return True",
            "    if source == 'timestamp' and target == 'date':",
            "        return True",
            "    source_decimal = _cf_decimal_parts(source)",
            "    target_decimal = _cf_decimal_parts(target)",
            "    if source_decimal and target_decimal:",
            "        return source_decimal[0] >= target_decimal[0] and source_decimal[1] >= target_decimal[1]",
            "    return False",
            "",
            "def _cf_target_schema_map():",
            "    global _cf_schema_lookup_warning",
            "    try:",
            "        if not spark.catalog.tableExists(TARGET_TABLE):",
            "            return None",
            "        return _cf_schema_map(spark.table(TARGET_TABLE))",
            "    except Exception as exc:",
            "        _cf_schema_lookup_warning = 'target_schema_unavailable: ' + str(exc)[:1000]",
            "        return None",
            "",
            "def _cf_schema_diff(source_schema, target_schema):",
            "    if target_schema is None:",
            "        warnings = [_cf_schema_lookup_warning] if _cf_schema_lookup_warning else []",
            "        return {",
            "            'status': 'new_or_unknown',",
            "            'schema_policy': _CF_SCHEMA_POLICY,",
            "            'source_schema': source_schema,",
            "            'target_schema': None,",
            "            'added_columns': [],",
            "            'removed_columns': [],",
            "            'type_changes': [],",
            "            'allow_type_widening': _CF_ALLOW_TYPE_WIDENING,",
            "            'warnings': warnings,",
            "        }",
            "    added_columns = sorted(column for column in source_schema if column not in target_schema)",
            "    removed_columns = sorted(",
            "        column for column in target_schema if column not in source_schema and column not in _CF_IGNORED_TARGET_ONLY_COLUMNS",
            "    )",
            "    type_changes = []",
            "    for column in sorted(set(source_schema) & set(target_schema)):",
            "        source_type = source_schema[column]",
            "        target_type = target_schema[column]",
            "        if source_type == target_type:",
            "            continue",
            "        allowed = bool(_CF_ALLOW_TYPE_WIDENING and _cf_is_type_widening(source_type, target_type))",
            "        type_changes.append(",
            "            {",
            "                'column': column,",
            "                'source': source_type,",
            "                'target': target_type,",
            "                'allowed': allowed,",
            "                'change': 'type_widening' if allowed else 'type_change',",
            "            }",
            "        )",
            "    return {",
            "        'status': 'checked',",
            "        'schema_policy': _CF_SCHEMA_POLICY,",
            "        'source_schema': source_schema,",
            "        'target_schema': target_schema,",
            "        'added_columns': added_columns,",
            "        'removed_columns': removed_columns,",
            "        'type_changes': type_changes,",
            "        'allow_type_widening': _CF_ALLOW_TYPE_WIDENING,",
            "        'warnings': [],",
            "    }",
            "",
            "def _cf_validate_schema_policy(dataframe=None):",
            "    global _cf_schema_changes",
            "    source_schema = _cf_schema_map(dataframe)",
            "    target_schema = _cf_target_schema_map()",
            "    changes = _cf_schema_diff(source_schema, target_schema)",
            "    changes['change_type'] = 'SCHEMA_POLICY'",
            "    changes['applied'] = True",
            "    blocking_type_changes = [item for item in changes['type_changes'] if not item.get('allowed')]",
            "    if _CF_SCHEMA_POLICY == 'strict' and (changes['added_columns'] or changes['removed_columns'] or changes['type_changes']):",
            "        changes['applied'] = False",
            "        _cf_schema_changes = changes",
            "        raise ValueError('Schema policy strict violation: ' + json.dumps(changes, sort_keys=True, separators=(',', ':')))",
            "    if _CF_SCHEMA_POLICY == 'additive_only' and (changes['removed_columns'] or blocking_type_changes):",
            "        changes['applied'] = False",
            "        _cf_schema_changes = changes",
            "        raise ValueError('Schema policy additive_only violation: ' + json.dumps(changes, sort_keys=True, separators=(',', ':')))",
            "    if _CF_SCHEMA_POLICY == 'permissive' and blocking_type_changes:",
            "        changes['applied'] = False",
            "        _cf_schema_changes = changes",
            "        raise ValueError('Schema policy permissive violation: ' + json.dumps(changes, sort_keys=True, separators=(',', ':')))",
            "    _cf_schema_changes = changes",
            "",
            "def _cf_acquire_lock():",
            "    global _cf_lock_acquired",
            "    if not _CF_LOCK_ENABLED:",
            "        return",
            "    lock_table = _cf_sql_table(EVIDENCE_SCHEMA, 'ctrl_ingestion_locks')",
            "    owner = _CF_LOCK_OWNER or 'fabric_notebook'",
            "    spark.sql(f'''",
            "MERGE INTO {lock_table} AS target",
            "USING (",
            "  SELECT",
            "    {_cf_sql_literal(TARGET_TABLE)} AS target_table,",
            "    {_cf_sql_literal(RUN_ID)} AS run_id,",
            "    {_cf_sql_literal(owner)} AS owner,",
            "    current_timestamp() AS acquired_at_utc,",
            "    current_timestamp() + INTERVAL {_CF_LOCK_TTL_MINUTES} MINUTES AS expires_at_utc,",
            "    {_CF_LOCK_TTL_MINUTES} AS ttl_minutes,",
            "    CAST(NULL AS TIMESTAMP) AS released_at_utc,",
            "    'ACTIVE' AS status",
            ") AS source",
            "ON target.target_table = source.target_table",
            "WHEN MATCHED AND (target.status <> 'ACTIVE' OR target.expires_at_utc < current_timestamp()) THEN UPDATE SET",
            "  target.run_id = source.run_id,",
            "  target.owner = source.owner,",
            "  target.acquired_at_utc = source.acquired_at_utc,",
            "  target.expires_at_utc = source.expires_at_utc,",
            "  target.ttl_minutes = source.ttl_minutes,",
            "  target.released_at_utc = source.released_at_utc,",
            "  target.status = source.status",
            "WHEN NOT MATCHED THEN INSERT (target_table, run_id, owner, acquired_at_utc, expires_at_utc, ttl_minutes, released_at_utc, status)",
            "VALUES (source.target_table, source.run_id, source.owner, source.acquired_at_utc, source.expires_at_utc, source.ttl_minutes, source.released_at_utc, source.status)",
            "''')",
            "    rows = spark.sql(",
            "        f'SELECT run_id, owner, status FROM {lock_table} '",
            "        f'WHERE target_table = {_cf_sql_literal(TARGET_TABLE)} '",
            "        'ORDER BY acquired_at_utc DESC LIMIT 1'",
            "    ).collect()",
            "    if not rows or rows[0]['run_id'] != RUN_ID or rows[0]['status'] != 'ACTIVE':",
            "        owner = rows[0]['owner'] if rows else 'unknown'",
            "        raise RuntimeError(f'Fabric lock is busy for {TARGET_TABLE}; owner={owner}')",
            "    _cf_lock_acquired = True",
            "",
            "def _cf_release_lock():",
            "    global _cf_lock_acquired",
            "    if not _CF_LOCK_ENABLED or not _cf_lock_acquired:",
            "        return",
            "    lock_table = _cf_sql_table(EVIDENCE_SCHEMA, 'ctrl_ingestion_locks')",
            "    try:",
            "        spark.sql(",
            "            f'UPDATE {lock_table} '",
            "            \"SET status = 'RELEASED', released_at_utc = current_timestamp() \"",
            "            f'WHERE target_table = {_cf_sql_literal(TARGET_TABLE)} AND run_id = {_cf_sql_literal(RUN_ID)}'",
            "        )",
            "    except Exception as exc:",
            "        print('ContractForge Fabric lock release failed: ' + str(exc)[:1000])",
            "    finally:",
            "        _cf_lock_acquired = False",
            "",
            "def _cf_add_quality_result(rule_name, status, severity, failed_count, observed_value=None, message=None, details=None):",
            "    _cf_quality_results.append(",
            "        {",
            "            'rule_name': rule_name,",
            "            'status': status,",
            "            'severity': severity,",
            "            'failed_count': int(failed_count or 0),",
            "            'observed_value': observed_value,",
            "            'checked_at_utc': _cf_now(),",
            "            'message': message,",
            "            'details_json': json.dumps(details or {}, sort_keys=True, separators=(',', ':')),",
            "        }",
            "    )",
            "",
            "def _cf_record_quality_evidence():",
            "    global _cf_quality_evidence_recorded",
            "    if _cf_quality_evidence_recorded:",
            "        return",
            "    _cf_quality_evidence_recorded = True",
            "    for result in _cf_quality_results:",
            "        _cf_insert_evidence(",
            "            'ctrl_ingestion_quality',",
            "            {",
            "                'run_id': RUN_ID,",
            "                'target_table': TARGET_TABLE,",
            "                'rule_name': result['rule_name'],",
            "                'status': result['status'],",
            "                'severity': result['severity'],",
            "                'failed_count': result['failed_count'],",
            "                'observed_value': result['observed_value'],",
            "                'checked_at_utc': result['checked_at_utc'],",
            "                'message': result['message'],",
            "                'details_json': result['details_json'],",
            "            },",
            "        )",
            "",
            "def _cf_record_quarantine_evidence(rule_name, failed_dataframe, reason):",
            "    if failed_dataframe is None:",
            "        return",
            "    for row in failed_dataframe.toJSON().collect():",
            "        quarantined_at = _cf_now()",
            "        _cf_insert_evidence(",
            "            'ctrl_ingestion_quarantine',",
            "            {",
            "                'run_id': RUN_ID,",
            "                'target_table': TARGET_TABLE,",
            "                'rule_name': rule_name,",
            "                'error_reason': reason,",
            "                'record_payload': row,",
            "                'record_ref': None,",
            "                'reason': reason,",
            "                'quarantined_at_utc': quarantined_at,",
            "            },",
            "        )",
            "",
            "def _cf_schema_fields(dataframe):",
            "    if dataframe is None:",
            "        return []",
            "    return [{'name': field.name, 'type': field.dataType.simpleString()} for field in dataframe.schema.fields]",
            "",
            "def _cf_openlineage_dataset(name, fields):",
            "    return {",
            "        'namespace': _CF_LINEAGE_NAMESPACE,",
            "        'name': name,",
            "        'facets': {",
            "            'schema': {",
            "                '_producer': 'contractforge-fabric',",
            "                '_schemaURL': 'https://openlineage.io/spec/facets/1-0-0/SchemaDatasetFacet.json',",
            "                'fields': fields,",
            "            }",
            "        },",
            "    }",
            "",
            "def _cf_openlineage_event(status, finished_at, input_fields, output_fields):",
            "    output = _cf_openlineage_dataset(_CF_LINEAGE_TARGET_NAME, output_fields)",
            "    output['facets']['dataQualityMetrics'] = {",
            "        '_producer': 'contractforge-fabric',",
            "        '_schemaURL': 'https://openlineage.io/spec/facets/1-0-0/DataQualityMetricsOutputDatasetFacet.json',",
            "        'rowCount': _cf_rows_written,",
            "    }",
            "    return {",
            "        'eventType': 'COMPLETE' if status == 'SUCCESS' else 'FAIL',",
            "        'eventTime': finished_at.isoformat(),",
            "        'producer': 'contractforge-fabric',",
            "        'schemaURL': 'https://openlineage.io/spec/1-0-5/OpenLineage.json',",
            "        'run': {",
            "            'runId': RUN_ID,",
            "            'facets': {",
            "                'processing_engine': {",
            "                    '_producer': 'contractforge-fabric',",
            "                    '_schemaURL': 'https://openlineage.io/spec/facets/1-0-0/ProcessingEngineRunFacet.json',",
            "                    'name': 'spark',",
            "                    'version': spark.version,",
            "                }",
            "            },",
            "        },",
            "        'job': {'namespace': _CF_LINEAGE_NAMESPACE, 'name': _CF_LINEAGE_JOB_NAME},",
            "        'inputs': [_cf_openlineage_dataset(_CF_LINEAGE_SOURCE_NAME, input_fields)],",
            "        'outputs': [output],",
            "        'facets': {",
            "            'contractforge': {",
            "                '_producer': 'contractforge-fabric',",
            "                '_schemaURL': 'https://openlineage.io/spec/facets/1-0-0/RunFacet.json',",
            "                'adapter': 'fabric',",
            "                'mode': WRITE_MODE,",
            f"                'layer': {json.dumps(contract.target.layer)},",
            "                'rowsRead': _cf_rows_read,",
            "                'rowsWritten': _cf_rows_written,",
            "                'rowsQuarantined': _cf_rows_quarantined,",
            "                'startedAt': _cf_started_at_utc.isoformat(),",
            "                'finishedAt': finished_at.isoformat(),",
            "            }",
            "        },",
            "    }",
            "",
            "def _cf_record_lineage_evidence(input_dataframe=None, output_dataframe=None, status='SUCCESS'):",
            "    global _cf_lineage_evidence_recorded",
            "    if _cf_lineage_evidence_recorded:",
            "        return",
            "    _cf_lineage_evidence_recorded = True",
            "    finished_at = _cf_now()",
            "    event = _cf_openlineage_event(status, finished_at, _cf_schema_fields(input_dataframe), _cf_schema_fields(output_dataframe))",
            "    _cf_insert_evidence(",
            "        'ctrl_ingestion_lineage',",
            "        {",
            "            'run_id': RUN_ID,",
            "            'event_time_utc': finished_at,",
            "            'event_type': event['eventType'],",
            "            'target_table': TARGET_TABLE,",
            "            'source_table': _CF_LINEAGE_SOURCE_NAME,",
            "            'source_name': _CF_LINEAGE_SOURCE_NAME,",
            "            'namespace': _CF_LINEAGE_NAMESPACE,",
            "            'producer': 'contractforge-fabric',",
            "            'event_json': json.dumps(event, sort_keys=True, separators=(',', ':')),",
            "        },",
            "    )",
            "",
            "def _cf_state_watermark_candidate(dataframe):",
            "    if not _CF_STATE_WATERMARK_COLUMN or dataframe is None:",
            "        return None",
            "    if _CF_STATE_WATERMARK_COLUMN not in dataframe.columns:",
            "        return None",
            "    rows = dataframe.selectExpr(f'max({_cf_sql_identifier(_CF_STATE_WATERMARK_COLUMN)}) AS watermark_value').collect()",
            "    if not rows:",
            "        return None",
            "    value = rows[0]['watermark_value']",
            "    return None if value is None else str(value)",
            "",
            "def _cf_record_state_evidence(dataframe=None):",
            "    global _cf_state_evidence_recorded",
            "    if _cf_state_evidence_recorded:",
            "        return",
            "    _cf_state_evidence_recorded = True",
            "    completed_at = _cf_now()",
            "    watermark_value = _cf_state_watermark_candidate(dataframe)",
            "    _cf_insert_evidence(",
            "        'ctrl_ingestion_state',",
            "        {",
            "            'target_table': TARGET_TABLE,",
            "            'watermark_column': _CF_STATE_WATERMARK_COLUMN,",
            "            'watermark_value': watermark_value,",
            "            'last_success_at_utc': completed_at,",
            "            'last_run_id': RUN_ID,",
            "            'last_status': 'SUCCESS',",
            "            'last_rows_written': _cf_rows_written,",
            "            'last_error_message': None,",
            "            'parent_run_id': None,",
            "            'run_group_id': None,",
            "            'master_job_id': None,",
            "            'master_run_id': None,",
            "            'last_table_version': None,",
            "            'last_write_completed_at_utc': completed_at,",
            "            'last_watermark_candidate': watermark_value,",
            "            'last_updated_at_utc': completed_at,",
            "        },",
            "    )",
            "",
            "def _cf_record_source_metadata_evidence(dataframe=None):",
            "    global _cf_source_metadata_evidence_recorded",
            "    if _cf_source_metadata_evidence_recorded:",
            "        return",
            "    _cf_source_metadata_evidence_recorded = True",
            "    captured_at = _cf_now()",
            "    metadata = json.loads(json.dumps(_CF_SOURCE_METADATA))",
            "    metrics = metadata.setdefault('source_metrics', {})",
            "    metrics['rows_read'] = _cf_rows_read",
            "    metrics['columns_read'] = len(dataframe.columns) if dataframe is not None else 0",
            "    metadata['source_schema'] = {",
            "        'columns': [",
            "            {'name': field.name, 'type': field.dataType.simpleString(), 'nullable': bool(field.nullable)}",
            "            for field in dataframe.schema.fields",
            "        ] if dataframe is not None else []",
            "    }",
            "    _cf_insert_evidence(",
            "        'ctrl_ingestion_metadata',",
            "        {",
            "            'component': 'source',",
            "            'framework_version': 'contractforge-fabric',",
            "            'ctrl_schema_version': 1,",
            "            'updated_at_utc': captured_at,",
            "            'run_id': RUN_ID,",
            "            'target_table': TARGET_TABLE,",
            "            'source_metadata_json': json.dumps(metadata, sort_keys=True, separators=(',', ':')),",
            "            'captured_at_utc': captured_at,",
            "        },",
            "    )",
            "",
            "def _cf_record_schema_change_evidence(dataframe=None):",
            "    global _cf_schema_change_evidence_recorded, _cf_schema_changes",
            "    if _cf_schema_change_evidence_recorded:",
            "        return",
            "    _cf_schema_change_evidence_recorded = True",
            "    changed_at = _cf_now()",
            "    schema_after = _cf_schema_fields(dataframe)",
            "    if not _cf_schema_changes:",
            "        _cf_schema_changes = {",
            "            'change_type': 'OBSERVED_SCHEMA',",
            "            'target_table': TARGET_TABLE,",
            "            'schema_after': schema_after,",
            "            'schema_policy': _CF_SCHEMA_POLICY,",
            "            'status': 'observed_only',",
            "            'applied': True,",
            "        }",
            "    else:",
            "        _cf_schema_changes = dict(_cf_schema_changes)",
            "        _cf_schema_changes['target_table'] = TARGET_TABLE",
            "        _cf_schema_changes['schema_after'] = schema_after",
            "    _cf_insert_evidence(",
            "        'ctrl_ingestion_schema_changes',",
            "        {",
            "            'run_id': RUN_ID,",
            "            'change_ts_utc': changed_at,",
            "            'target_table': TARGET_TABLE,",
            "            'change_type': _cf_schema_changes.get('change_type', 'SCHEMA_POLICY'),",
            "            'column_name': None,",
            "            'source_type': None,",
            "            'target_type': None,",
            "            'applied': bool(_cf_schema_changes.get('applied', True)),",
            "            'details_json': json.dumps({'schema_policy': _CF_SCHEMA_POLICY, 'write_mode': WRITE_MODE, 'status': _cf_schema_changes.get('status')}, sort_keys=True, separators=(',', ':')),",
            "            'payload_json': json.dumps(_cf_schema_changes, sort_keys=True, separators=(',', ':')),",
            "            'changed_at_utc': changed_at,",
            "            'framework_version': 'contractforge-fabric',",
            "            'ctrl_schema_version': 1,",
            "        },",
            "    )",
            "",
            "def _cf_explain_plan_text(dataframe):",
            "    if dataframe is None:",
            "        return None",
            "    try:",
            "        return str(dataframe._jdf.queryExecution().toString())[:32000]",
            "    except Exception as exc:",
            "        return 'EXPLAIN_UNAVAILABLE: ' + str(exc)[:1000]",
            "",
            "def _cf_record_explain_evidence(dataframe=None):",
            "    global _cf_explain_evidence_recorded",
            "    if _cf_explain_evidence_recorded:",
            "        return",
            "    _cf_explain_evidence_recorded = True",
            "    plan_text = _cf_explain_plan_text(dataframe)",
            "    if not plan_text:",
            "        return",
            "    _cf_insert_evidence(",
            "        'ctrl_ingestion_explain',",
            "        {",
            "            'run_id': RUN_ID,",
            "            'target_table': TARGET_TABLE,",
            "            'source_table': _CF_LINEAGE_SOURCE_NAME,",
            "            'mode': WRITE_MODE,",
            "            'explain_format': 'spark_query_execution',",
            "            'plan_text': plan_text,",
            "            'captured_at_utc': _cf_now(),",
            "        },",
            "    )",
            "",
            "def _cf_record_operations_evidence(status='RECORDED'):",
            "    global _cf_operations_evidence_recorded",
            "    if _cf_operations_evidence_recorded:",
            "        return",
            "    _cf_operations_evidence_recorded = True",
            "    payload = json.loads(json.dumps(_CF_OPERATIONS_PAYLOAD))",
            "    if not payload:",
            "        return",
            "    recorded_at = _cf_now()",
            "    _cf_insert_evidence(",
            "        'ctrl_ingestion_operations',",
            "        {",
            "            'run_id': RUN_ID,",
            "            'target_table': TARGET_TABLE,",
            "            'criticality': payload.get('criticality'),",
            "            'expected_frequency': payload.get('expected_frequency'),",
            "            'freshness_sla_minutes': payload.get('freshness_sla_minutes'),",
            "            'alert_on_failure': payload.get('alert_on_failure'),",
            "            'alert_on_quality_fail': payload.get('alert_on_quality_fail'),",
            "            'runbook_url': payload.get('runbook_url'),",
            "            'ownership_json': json.dumps(payload.get('ownership') or {}, sort_keys=True, separators=(',', ':')),",
            "            'owners_json': json.dumps(payload.get('owners') or [], sort_keys=True, separators=(',', ':')),",
            "            'groups_json': json.dumps(payload.get('groups') or [], sort_keys=True, separators=(',', ':')),",
            "            'tags_json': json.dumps(payload.get('tags') or {}, sort_keys=True, separators=(',', ':')),",
            "            'status': status,",
            "            'recorded_at_utc': recorded_at,",
            "            'framework_version': 'contractforge-fabric',",
            "            'ctrl_schema_version': 1,",
            "        },",
            "    )",
            "",
            "def _cf_record_annotations_evidence(status='VALIDATED'):",
            "    global _cf_annotations_evidence_recorded",
            "    if _cf_annotations_evidence_recorded:",
            "        return",
            "    _cf_annotations_evidence_recorded = True",
            "    captured_at = _cf_now()",
            "    for change in _CF_ANNOTATION_STEPS:",
            "        _cf_insert_evidence(",
            "            'ctrl_ingestion_annotations',",
            "            {",
            "                'run_id': RUN_ID,",
            "                'target_table': TARGET_TABLE,",
            "                'annotation_scope': change.get('annotation_scope'),",
            "                'annotation_type': change.get('annotation_type'),",
            "                'column_name': change.get('column_name'),",
            "                'key': change.get('key'),",
            "                'previous_value': None,",
            "                'value': change.get('value'),",
            "                'status': status,",
            "                'error_message': None,",
            "                'applied_sql': 'fabric_catalog_annotation_plan',",
            "                'annotation_ts_utc': captured_at,",
            "                'annotation_date': captured_at.date(),",
            "                'framework_version': 'contractforge-fabric',",
            "                'ctrl_schema_version': 1,",
            "            },",
            "        )",
            "",
            "def _cf_record_access_evidence(status='VALIDATED'):",
            "    global _cf_access_evidence_recorded",
            "    if _cf_access_evidence_recorded:",
            "        return",
            "    _cf_access_evidence_recorded = True",
            "    captured_at = _cf_now()",
            "    for step in _CF_ACCESS_STEPS:",
            "        payload = {key: value for key, value in step.items() if key != 'planned_statement'}",
            "        access_ref = step.get('principal') or step.get('column_name') or step.get('access_type')",
            "        _cf_insert_evidence(",
            "            'ctrl_ingestion_access',",
            "            {",
            "                'access_run_id': f\"{RUN_ID}:{step.get('action')}:{access_ref}\",",
            "                'run_id': RUN_ID,",
            "                'target_table': TARGET_TABLE,",
            "                'action': step.get('action'),",
            "                'access_type': step.get('access_type'),",
            "                'principal': step.get('principal'),",
            "                'privilege': step.get('privilege'),",
            "                'column_name': step.get('column_name'),",
            "                'function_name': step.get('function_name'),",
            "                'object_name': step.get('object_name'),",
            "                'status': status,",
            "                'error_message': None,",
            "                'applied_sql': step.get('applied_sql'),",
            "                'previous_value': step.get('previous_value'),",
            "                'new_value': step.get('new_value'),",
            "                'mode': step.get('mode'),",
            "                'drift_policy': step.get('drift_policy'),",
            "                'revoke_unmanaged': bool(step.get('revoke_unmanaged')),",
            "                'access_ts_utc': captured_at,",
            "                'access_date': captured_at.date(),",
            "                'payload_json': json.dumps(payload, sort_keys=True, separators=(',', ':')),",
            "                'applied_at_utc': captured_at,",
            "                'framework_version': 'contractforge-fabric',",
            "                'ctrl_schema_version': 1,",
            "            },",
            "        )",
            "",
            "def _cf_record_run_evidence(status, error_message=None):",
            "    finished_at = _cf_now()",
            "    _cf_insert_evidence(",
            "        'ctrl_ingestion_runs',",
            "        {",
            "            'run_id': RUN_ID,",
            "            'run_ts_utc': _cf_started_at_utc,",
            "            'run_date': _cf_started_at_utc.date(),",
            "            'runtime_entrypoint': 'fabric_notebook',",
            f"            'layer': {json.dumps(contract.target.layer)},",
            "            'source_type': SOURCE_TYPE,",
            "            'target_table': TARGET_TABLE,",
            "            'mode': WRITE_MODE,",
            "            'status': status,",
            "            'rows_read': _cf_rows_read,",
            "            'rows_written': _cf_rows_written,",
            "            'rows_quarantined': _cf_rows_quarantined,",
            "            'started_at_utc': _cf_started_at_utc,",
            "            'finished_at_utc': finished_at,",
            "            'duration_seconds': (finished_at - _cf_started_at_utc).total_seconds(),",
            "            'quality_status': _cf_quality_status,",
            "            'schema_policy': _CF_SCHEMA_POLICY,",
            "            'schema_changes_json': json.dumps(_cf_schema_changes, sort_keys=True, separators=(',', ':')) if _cf_schema_changes else None,",
            "            'write_committed': status == 'SUCCESS',",
            "            'error_message': error_message,",
            "            'metrics_source': 'fabric_notebook',",
            "            'framework_version': 'contractforge-fabric',",
            "            'ctrl_schema_version': 1,",
            "            'runtime_type': 'fabric_notebook',",
            "        },",
            "    )",
            "",
            "def _cf_record_error_evidence(error):",
            "    occurred_at = _cf_now()",
            "    _cf_insert_evidence(",
            "        'ctrl_ingestion_errors',",
            "        {",
            "            'run_id': RUN_ID,",
            "            'error_ts_utc': occurred_at,",
            "            'error_date': occurred_at.date(),",
            "            'target_table': TARGET_TABLE,",
            "            'source_type': SOURCE_TYPE,",
            "            'mode': WRITE_MODE,",
            "            'status': 'FAILED',",
            "            'error_type': type(error).__name__,",
            "            'error_class': error.__class__.__module__ + '.' + error.__class__.__name__,",
            "            'error_message': str(error),",
            "            'stack_trace': traceback.format_exc(),",
            "            'occurred_at_utc': occurred_at,",
            "            'framework_version': 'contractforge-fabric',",
            "            'ctrl_schema_version': 1,",
            "            'runtime_type': 'fabric_notebook',",
            "        },",
            "    )",
        ]
    )


def _bootstrap_statements() -> list[str]:
    sql = "\n".join(
        [
            render_create_evidence_tables_sql(schema="__CF_EVIDENCE_SCHEMA__", create_schema=True),
            render_create_state_tables_sql(schema="__CF_EVIDENCE_SCHEMA__", create_schema=False),
        ]
    )
    return [
        statement.strip().rstrip(";")
        for statement in sql.split(";")
        if statement.strip()
    ]


__all__ = ["render_notebook_evidence_setup"]
