"""Platform-neutral connector helpers."""

from contractforge_core.connectors.http_files import (
    HTTP_FILE_TYPES,
    cleanup_http_file_downloads,
    download_http_file,
    http_file_format,
    http_file_headers,
    http_file_params,
    http_file_reader_options,
    http_file_url,
    is_http_file_source,
    read_http_file_payload,
)
from contractforge_core.connectors.catalog import (
    CATALOG_SOURCE_TYPES,
    LogicalTableReference,
    TableRefResolver,
    catalog_source_query,
    catalog_source_table_or_path,
    has_table_reference_placeholders,
    is_catalog_source,
    parse_logical_table_reference,
    render_table_reference_placeholders,
    source_logical_table_reference,
)
from contractforge_core.connectors.files import (
    FILE_SOURCE_TYPES,
    OBJECT_STORAGE_TYPES,
    file_reader_options,
    file_source_format,
    is_file_source,
    normalize_file_format,
    object_storage_provider,
)
from contractforge_core.connectors.streams import (
    AVAILABLE_NOW_STREAM_TYPES,
    BOUNDED_STREAM_TYPES,
    STREAM_SOURCE_TYPES,
    eventhubs_bounded_options,
    is_available_now_stream_source,
    is_bounded_stream_source,
    is_eventhubs_stream_source,
    is_kafka_stream_source,
    kafka_bounded_options,
    stream_source_format,
)
from contractforge_core.connectors.sharing import delta_share_options, is_delta_share_source
from contractforge_core.connectors.databases import JDBC_CONNECTORS, jdbc_common_options, validate_jdbc_source
from contractforge_core.connectors.native_passthrough import (
    is_native_passthrough_source,
    native_passthrough_descriptor,
    redact_secret_fields,
)
from contractforge_core.connectors.metadata import (
    diagnose_source_connectors,
    list_source_connector_details,
    source_capabilities,
    source_connector_details,
    source_metadata_from_contract,
    source_metadata_from_mapping,
    source_provider,
)
from contractforge_core.connectors.databases import (
    generate_rds_iam_auth_token,
    infer_aws_region_from_rds_host,
    parse_jdbc_host_port,
    rds_iam_review_options,
)
from contractforge_core.connectors.api.rest import (
    REST_API_CONNECTORS,
    is_rest_api_connector,
    read_rest_api_records,
    rest_api_descriptor,
    rest_request_headers,
)

__all__ = [
    "HTTP_FILE_TYPES",
    "cleanup_http_file_downloads",
    "download_http_file",
    "read_rest_api_records",
    "rest_request_headers",
    "JDBC_CONNECTORS",
    "CATALOG_SOURCE_TYPES",
    "LogicalTableReference",
    "TableRefResolver",
    "AVAILABLE_NOW_STREAM_TYPES",
    "BOUNDED_STREAM_TYPES",
    "STREAM_SOURCE_TYPES",
    "FILE_SOURCE_TYPES",
    "OBJECT_STORAGE_TYPES",
    "REST_API_CONNECTORS",
    "catalog_source_query",
    "catalog_source_table_or_path",
    "delta_share_options",
    "diagnose_source_connectors",
    "eventhubs_bounded_options",
    "file_reader_options",
    "file_source_format",
    "generate_rds_iam_auth_token",
    "has_table_reference_placeholders",
    "http_file_format",
    "http_file_headers",
    "http_file_params",
    "http_file_reader_options",
    "http_file_url",
    "read_http_file_payload",
    "infer_aws_region_from_rds_host",
    "is_http_file_source",
    "is_available_now_stream_source",
    "is_bounded_stream_source",
    "is_catalog_source",
    "is_delta_share_source",
    "is_eventhubs_stream_source",
    "is_file_source",
    "is_kafka_stream_source",
    "stream_source_format",
    "jdbc_common_options",
    "list_source_connector_details",
    "is_native_passthrough_source",
    "is_rest_api_connector",
    "kafka_bounded_options",
    "native_passthrough_descriptor",
    "parse_jdbc_host_port",
    "parse_logical_table_reference",
    "redact_secret_fields",
    "render_table_reference_placeholders",
    "rest_api_descriptor",
    "normalize_file_format",
    "object_storage_provider",
    "rds_iam_review_options",
    "source_capabilities",
    "source_connector_details",
    "source_metadata_from_contract",
    "source_metadata_from_mapping",
    "source_provider",
    "source_logical_table_reference",
    "validate_jdbc_source",
]
