"""BigQuery evidence table rendering."""

from __future__ import annotations

from contractforge_core.evidence import EVIDENCE_TABLES
from contractforge_gcp.rendering.names import table_prefix


def render_bigquery_evidence_ddl(*, project_id: str | None, dataset: str) -> str:
    prefix = table_prefix(project_id, dataset)
    return "\n".join(
        [
            f"CREATE SCHEMA IF NOT EXISTS `{prefix}`;",
            "",
            f"CREATE TABLE IF NOT EXISTS `{prefix}.contractforge_run_evidence` (",
            "  run_id STRING NOT NULL,",
            "  contract_name STRING NOT NULL,",
            "  target_table STRING NOT NULL,",
            "  adapter STRING NOT NULL,",
            "  status STRING NOT NULL,",
            "  started_at TIMESTAMP,",
            "  finished_at TIMESTAMP,",
            "  total_bytes_processed INT64,",
            "  total_bytes_billed INT64,",
            "  total_slot_ms INT64,",
            "  job_id STRING,",
            "  statement_type STRING,",
            "  inserted_rows INT64,",
            "  updated_rows INT64,",
            "  deleted_rows INT64,",
            "  error_message STRING",
            ");",
            "",
            f"CREATE TABLE IF NOT EXISTS `{prefix}.contractforge_quality_evidence` (",
            "  run_id STRING NOT NULL,",
            "  contract_name STRING NOT NULL,",
            "  rule_name STRING NOT NULL,",
            "  rule_type STRING NOT NULL,",
            "  status STRING NOT NULL,",
            "  failed_rows INT64,",
            "  evaluated_at TIMESTAMP",
            ");",
            "",
            f"CREATE TABLE IF NOT EXISTS `{prefix}.contractforge_annotation_evidence` (",
            "  run_id STRING NOT NULL,",
            "  contract_name STRING NOT NULL,",
            "  target_table STRING NOT NULL,",
            "  annotation_scope STRING NOT NULL,",
            "  annotation_type STRING NOT NULL,",
            "  column_name STRING,",
            "  key STRING NOT NULL,",
            "  value STRING,",
            "  status STRING NOT NULL,",
            "  error_message STRING,",
            "  applied_sql STRING,",
            "  annotation_ts TIMESTAMP,",
            "  annotation_date DATE,",
            "  framework_version STRING,",
            "  ctrl_schema_version INT64",
            ");",
            "",
            f"CREATE TABLE IF NOT EXISTS `{prefix}.contractforge_schema_evidence` (",
            "  run_id STRING NOT NULL,",
            "  contract_name STRING NOT NULL,",
            "  target_table STRING NOT NULL,",
            "  schema_policy STRING NOT NULL,",
            "  status STRING NOT NULL,",
            "  added_columns ARRAY<STRING>,",
            "  removed_columns ARRAY<STRING>,",
            "  type_changes_json STRING,",
            "  schema_changes_json STRING,",
            "  evaluated_at TIMESTAMP,",
            "  error_message STRING",
            ");",
            "",
            f"CREATE TABLE IF NOT EXISTS `{prefix}.contractforge_governance_evidence` (",
            "  run_id STRING NOT NULL,",
            "  contract_name STRING NOT NULL,",
            "  target_table STRING NOT NULL,",
            "  governance_surface STRING NOT NULL,",
            "  operation STRING NOT NULL,",
            "  subject STRING,",
            "  status STRING NOT NULL,",
            "  details_json STRING,",
            "  evidence_ts TIMESTAMP,",
            "  error_message STRING",
            ");",
            "",
            f"CREATE TABLE IF NOT EXISTS `{prefix}.contractforge_lineage_evidence` (",
            "  run_id STRING NOT NULL,",
            "  target_table STRING NOT NULL,",
            "  source_name STRING NOT NULL,",
            "  event_json STRING NOT NULL,",
            "  event_time TIMESTAMP,",
            "  adapter STRING NOT NULL",
            ");",
            "",
            f"CREATE TABLE IF NOT EXISTS `{prefix}.{EVIDENCE_TABLES['deployments']}` (",
            "  deployment_id STRING NOT NULL,",
            "  deployment_step_id STRING NOT NULL,",
            "  deployment_hash STRING NOT NULL,",
            "  deployment_ts_utc TIMESTAMP,",
            "  deployment_date DATE,",
            "  deployment_status STRING,",
            "  adapter STRING,",
            "  platform STRING,",
            "  subtarget STRING,",
            "  project_name STRING,",
            "  project_path STRING,",
            "  environment_key STRING,",
            "  environment_path STRING,",
            "  contract_name STRING,",
            "  contract_path STRING,",
            "  contract_layer STRING,",
            "  target_table STRING,",
            "  mode STRING,",
            "  action STRING,",
            "  artifact_kind STRING,",
            "  artifact_name STRING,",
            "  artifact_id STRING,",
            "  artifact_uri STRING,",
            "  definition_hash STRING,",
            "  previous_definition_hash STRING,",
            "  contract_hash STRING,",
            "  environment_hash STRING,",
            "  manifest_hash STRING,",
            "  package_versions_json STRING,",
            "  git_commit STRING,",
            "  deployed_by STRING,",
            "  deployment_config_json STRING,",
            "  deployment_result_json STRING,",
            "  created_at_utc TIMESTAMP,",
            "  framework_version STRING,",
            "  ctrl_schema_version INT64",
            ")",
            "PARTITION BY deployment_date;",
            "",
        ]
    )
