"""AWS Glue runtime argument names managed by ContractForge."""

CONTRACT_URI_ARG = "CONTRACTFORGE_CONTRACT_URI"
ENVIRONMENT_URI_ARG = "CONTRACTFORGE_ENVIRONMENT_URI"
RUNTIME_MODE_ARG = "CONTRACTFORGE_RUNTIME_MODE"

__all__ = ["CONTRACT_URI_ARG", "ENVIRONMENT_URI_ARG", "RUNTIME_MODE_ARG"]
